-- Ingredient "components" (sections) + per-line IDs on recipe_ingredients.
-- Run once in Supabase SQL Editor (after KitchenOS v2 / owner-scoped recipes).
--
-- Why: composite PK (recipe_id, ingredient_id) blocked the same ingredient on
-- multiple lines; sections need named groups with ordering.
--
-- After this migration, update clients that used on_conflict=recipe_id,ingredient_id.

-- ---------------------------------------------------------------------------
-- Section headers per recipe
-- ---------------------------------------------------------------------------
create table if not exists public.recipe_ingredient_sections (
  id uuid primary key default gen_random_uuid(),
  recipe_id bigint not null references public.recipes (id) on delete cascade,
  title text not null default '',
  sort_order int not null default 0,
  created_at timestamptz default now()
);

create index if not exists recipe_ingredient_sections_recipe_sort
  on public.recipe_ingredient_sections (recipe_id, sort_order);

-- ---------------------------------------------------------------------------
-- recipe_ingredients: surrogate PK + section + line order
-- ---------------------------------------------------------------------------
do $$
begin
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'recipe_ingredients'
      and column_name = 'id'
  ) then
    alter table public.recipe_ingredients drop constraint if exists recipe_ingredients_pkey;

    alter table public.recipe_ingredients
      add column id bigint generated by default as identity primary key;
  end if;
end
$$;

alter table public.recipe_ingredients
  add column if not exists section_id uuid references public.recipe_ingredient_sections (id) on delete set null;

alter table public.recipe_ingredients
  add column if not exists line_sort_order int not null default 0;

create index if not exists recipe_ingredients_recipe_section_sort
  on public.recipe_ingredients (recipe_id, section_id, line_sort_order);

-- Existing rows keep line_sort_order = 0; the app sorts by name as a tiebreak.

-- ---------------------------------------------------------------------------
-- RLS (matches recipe_ingredients ownership via recipes.owner_id)
-- ---------------------------------------------------------------------------
alter table public.recipe_ingredient_sections enable row level security;

drop policy if exists "risec_select" on public.recipe_ingredient_sections;

drop policy if exists "risec_insert" on public.recipe_ingredient_sections;

drop policy if exists "risec_update" on public.recipe_ingredient_sections;

drop policy if exists "risec_delete" on public.recipe_ingredient_sections;

create policy "risec_select" on public.recipe_ingredient_sections for select to authenticated using (
  exists (
    select 1
    from public.recipes r
    where
      r.id = recipe_ingredient_sections.recipe_id
      and r.owner_id = auth.uid ()
  )
);

create policy "risec_insert" on public.recipe_ingredient_sections for insert to authenticated
with check (
  exists (
    select 1
    from public.recipes r
    where
      r.id = recipe_id
      and r.owner_id = auth.uid ()
  )
);

create policy "risec_update" on public.recipe_ingredient_sections for update to authenticated using (
  exists (
    select 1
    from public.recipes r
    where
      r.id = recipe_ingredient_sections.recipe_id
      and r.owner_id = auth.uid ()
  )
)
with check (
  exists (
    select 1
    from public.recipes r
    where
      r.id = recipe_id
      and r.owner_id = auth.uid ()
  )
);

create policy "risec_delete" on public.recipe_ingredient_sections for delete to authenticated using (
  exists (
    select 1
    from public.recipes r
    where
      r.id = recipe_ingredient_sections.recipe_id
      and r.owner_id = auth.uid ()
  )
);

comment on table public.recipe_ingredient_sections is 'Named ingredient groups (components) within a recipe.';

comment on column public.recipe_ingredients.section_id is 'Ingredient section; null = legacy single bucket before sections exist.';

comment on column public.recipe_ingredients.line_sort_order is 'Display order within (recipe, section).';
