-- KitchenOS v2: inventory by location, meal plans, per-user equipment, owner-scoped data.
-- Run in Supabase SQL Editor AFTER app/database/supabase_setup.sql (or merge into a fresh project).
-- If tables already exist with data, add owner_id in Dashboard or run UPDATEs after first login.

-- ---------------------------------------------------------------------------
-- Owner columns (nullable during migration; trigger fills on insert)
-- ---------------------------------------------------------------------------
alter table public.recipes add column if not exists owner_id uuid references auth.users (id) on delete cascade;
alter table public.ingredients add column if not exists owner_id uuid references auth.users (id) on delete cascade;
alter table public.shopping_items add column if not exists owner_id uuid references auth.users (id) on delete cascade;
alter table public.people add column if not exists owner_id uuid references auth.users (id) on delete cascade;

-- Ingredients: per-owner uniqueness (drop global unique on name if present)
alter table public.ingredients drop constraint if exists ingredients_name_key;
drop index if exists public.ingredients_name_unique;
create unique index if not exists ingredients_owner_name_lower
  on public.ingredients (owner_id, lower(name::text))
  where owner_id is not null;
create unique index if not exists ingredients_name_legacy_unique
  on public.ingredients (lower(name::text))
  where owner_id is null;

-- ---------------------------------------------------------------------------
-- set owner_id on insert when missing
-- ---------------------------------------------------------------------------
create or replace function public.kitchenos_set_owner_id ()
  returns trigger
  language plpgsql
  security definer
  set search_path = public
as $$
begin
  if new.owner_id is null and auth.uid () is not null then
    new.owner_id := auth.uid ();
  end if;
  return new;
end;
$$;

drop trigger if exists kitchenos_recipes_owner on public.recipes;
create trigger kitchenos_recipes_owner
before insert on public.recipes
for each row
execute function public.kitchenos_set_owner_id();

drop trigger if exists kitchenos_ingredients_owner on public.ingredients;
create trigger kitchenos_ingredients_owner
before insert on public.ingredients
for each row
execute function public.kitchenos_set_owner_id();

drop trigger if exists kitchenos_shopping_owner on public.shopping_items;
create trigger kitchenos_shopping_owner
before insert on public.shopping_items
for each row
execute function public.kitchenos_set_owner_id();

drop trigger if exists kitchenos_people_owner on public.people;
create trigger kitchenos_people_owner
before insert on public.people
for each row
execute function public.kitchenos_set_owner_id();

-- ---------------------------------------------------------------------------
-- Inventory: one row per ingredient per storage zone (per owner)
-- ---------------------------------------------------------------------------
create table if not exists public.inventory_items (
  id bigint generated by default as identity primary key,
  owner_id uuid references auth.users (id) on delete cascade,
  ingredient_id bigint not null references public.ingredients (id) on delete cascade,
  storage_location text not null check (
    storage_location in (
      'Fridge',
      'Freezer',
      'Shallow Pantry',
      'Deep Pantry',
      'Other'
    )
  ),
  quantity numeric,
  min_quantity numeric,
  max_quantity numeric,
  unit text,
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (owner_id, ingredient_id, storage_location)
);

drop trigger if exists kitchenos_inventory_owner on public.inventory_items;
create trigger kitchenos_inventory_owner
before insert on public.inventory_items
for each row
execute function public.kitchenos_set_owner_id();

alter table public.inventory_items add column if not exists min_quantity numeric;
alter table public.inventory_items add column if not exists max_quantity numeric;

-- ---------------------------------------------------------------------------
-- User equipment (catalog stays shared; toggles are per user)
-- ---------------------------------------------------------------------------
create table if not exists public.user_equipment (
  user_id uuid not null references auth.users (id) on delete cascade,
  equipment_id bigint not null references public.equipment (id) on delete cascade,
  has_item boolean not null default false,
  updated_at timestamptz default now(),
  primary key (user_id, equipment_id)
);

create or replace function public.kitchenos_user_equipment_set_uid ()
  returns trigger
  language plpgsql
  security definer
  set search_path = public
as $$
begin
  new.user_id := auth.uid ();
  return new;
end;
$$;

drop trigger if exists kitchenos_user_equipment_uid on public.user_equipment;
create trigger kitchenos_user_equipment_uid
before insert or update on public.user_equipment
for each row
execute function public.kitchenos_user_equipment_set_uid();

-- ---------------------------------------------------------------------------
-- Meal plans
-- ---------------------------------------------------------------------------
create table if not exists public.meal_plans (
  id bigint generated by default as identity primary key,
  owner_id uuid references auth.users (id) on delete cascade,
  week_start date not null,
  title text,
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (owner_id, week_start)
);

drop trigger if exists kitchenos_meal_plans_owner on public.meal_plans;
create trigger kitchenos_meal_plans_owner
before insert on public.meal_plans
for each row
execute function public.kitchenos_set_owner_id();

create table if not exists public.meal_plan_entries (
  id bigint generated by default as identity primary key,
  meal_plan_id bigint not null references public.meal_plans (id) on delete cascade,
  plan_date date not null,
  meal_slot text not null check (
    meal_slot in ('breakfast', 'lunch', 'dinner', 'snack', 'other')
  ),
  recipe_id bigint references public.recipes (id) on delete set null,
  label text,
  notes text,
  sort_order integer default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists meal_plan_entries_plan_idx on public.meal_plan_entries (meal_plan_id, plan_date);

-- ---------------------------------------------------------------------------
-- RLS: enable
-- ---------------------------------------------------------------------------
alter table public.inventory_items enable row level security;
alter table public.user_equipment enable row level security;
alter table public.meal_plans enable row level security;
alter table public.meal_plan_entries enable row level security;

-- ---------------------------------------------------------------------------
-- Drop legacy public policies
-- ---------------------------------------------------------------------------
drop policy if exists "Public read recipes" on public.recipes;
drop policy if exists "Public write recipes" on public.recipes;
drop policy if exists "Public update recipes" on public.recipes;
drop policy if exists "Public delete recipes" on public.recipes;
drop policy if exists "Public read ingredients" on public.ingredients;
drop policy if exists "Public write ingredients" on public.ingredients;
drop policy if exists "Public update ingredients" on public.ingredients;
drop policy if exists "Public delete ingredients" on public.ingredients;
drop policy if exists "Public read equipment" on public.equipment;
drop policy if exists "Public write equipment" on public.equipment;
drop policy if exists "Public update equipment" on public.equipment;
drop policy if exists "Public delete equipment" on public.equipment;
drop policy if exists "Public read shopping items" on public.shopping_items;
drop policy if exists "Public write shopping items" on public.shopping_items;
drop policy if exists "Public update shopping items" on public.shopping_items;
drop policy if exists "Public delete shopping items" on public.shopping_items;
drop policy if exists "Public read people" on public.people;
drop policy if exists "Public write people" on public.people;
drop policy if exists "Public update people" on public.people;
drop policy if exists "Public delete people" on public.people;
drop policy if exists "Public read recipe ingredients" on public.recipe_ingredients;
drop policy if exists "Public write recipe ingredients" on public.recipe_ingredients;
drop policy if exists "Public delete recipe ingredients" on public.recipe_ingredients;

-- ---------------------------------------------------------------------------
-- Recipes
-- ---------------------------------------------------------------------------
create policy "recipes_select_own" on public.recipes for select to authenticated
  using (owner_id = auth.uid ());

create policy "recipes_insert_own" on public.recipes for insert to authenticated
  with check (owner_id = auth.uid () or owner_id is null);

create policy "recipes_update_own" on public.recipes for update to authenticated
  using (owner_id = auth.uid ())
  with check (owner_id = auth.uid ());

create policy "recipes_delete_own" on public.recipes for delete to authenticated
  using (owner_id = auth.uid ());

-- ---------------------------------------------------------------------------
-- Ingredients
-- ---------------------------------------------------------------------------
create policy "ingredients_select_own" on public.ingredients for select to authenticated
  using (owner_id = auth.uid ());

create policy "ingredients_insert_own" on public.ingredients for insert to authenticated
  with check (owner_id = auth.uid () or owner_id is null);

create policy "ingredients_update_own" on public.ingredients for update to authenticated
  using (owner_id = auth.uid ())
  with check (owner_id = auth.uid ());

create policy "ingredients_delete_own" on public.ingredients for delete to authenticated
  using (owner_id = auth.uid ());

-- ---------------------------------------------------------------------------
-- Equipment catalog: readable by authenticated; writes only service role (no user policies)
-- ---------------------------------------------------------------------------
create policy "equipment_select_auth" on public.equipment for select to authenticated
  using (true);

-- ---------------------------------------------------------------------------
-- Shopping & people
-- ---------------------------------------------------------------------------
create policy "shopping_select_own" on public.shopping_items for select to authenticated
  using (owner_id = auth.uid ());

create policy "shopping_insert_own" on public.shopping_items for insert to authenticated
  with check (owner_id = auth.uid () or owner_id is null);

create policy "shopping_update_own" on public.shopping_items for update to authenticated
  using (owner_id = auth.uid ())
  with check (owner_id = auth.uid ());

create policy "shopping_delete_own" on public.shopping_items for delete to authenticated
  using (owner_id = auth.uid ());

create policy "people_select_own" on public.people for select to authenticated
  using (owner_id = auth.uid ());

create policy "people_insert_own" on public.people for insert to authenticated
  with check (owner_id = auth.uid () or owner_id is null);

create policy "people_update_own" on public.people for update to authenticated
  using (owner_id = auth.uid ())
  with check (owner_id = auth.uid ());

create policy "people_delete_own" on public.people for delete to authenticated
  using (owner_id = auth.uid ());

-- ---------------------------------------------------------------------------
-- Recipe ingredients (via parent recipe ownership)
-- ---------------------------------------------------------------------------
create policy "ri_select" on public.recipe_ingredients for select to authenticated
  using (
    exists (
      select 1
      from public.recipes r
      where r.id = recipe_ingredients.recipe_id
        and r.owner_id = auth.uid ()
    )
  );

create policy "ri_insert" on public.recipe_ingredients for insert to authenticated
  with check (
    exists (
      select 1
      from public.recipes r
      where r.id = recipe_ingredients.recipe_id
        and r.owner_id = auth.uid ()
    )
    and exists (
      select 1
      from public.ingredients i
      where i.id = recipe_ingredients.ingredient_id
        and i.owner_id = auth.uid ()
    )
  );

create policy "ri_delete" on public.recipe_ingredients for delete to authenticated
  using (
    exists (
      select 1
      from public.recipes r
      where r.id = recipe_ingredients.recipe_id
        and r.owner_id = auth.uid ()
    )
  );

create policy "ri_update" on public.recipe_ingredients for update to authenticated
  using (
    exists (
      select 1
      from public.recipes r
      where r.id = recipe_ingredients.recipe_id
        and r.owner_id = auth.uid ()
    )
  )
  with check (
    exists (
      select 1
      from public.recipes r
      where r.id = recipe_ingredients.recipe_id
        and r.owner_id = auth.uid ()
    )
    and exists (
      select 1
      from public.ingredients i
      where i.id = recipe_ingredients.ingredient_id
        and i.owner_id = auth.uid ()
    )
  );

-- ---------------------------------------------------------------------------
-- Inventory items
-- ---------------------------------------------------------------------------
create policy "inv_select" on public.inventory_items for select to authenticated
  using (owner_id = auth.uid ());

create policy "inv_insert" on public.inventory_items for insert to authenticated
  with check (owner_id = auth.uid () or owner_id is null);

create policy "inv_update" on public.inventory_items for update to authenticated
  using (owner_id = auth.uid ())
  with check (owner_id = auth.uid ());

create policy "inv_delete" on public.inventory_items for delete to authenticated
  using (owner_id = auth.uid ());

-- ---------------------------------------------------------------------------
-- User equipment
-- ---------------------------------------------------------------------------
create policy "ue_select" on public.user_equipment for select to authenticated
  using (user_id = auth.uid ());

create policy "ue_insert" on public.user_equipment for insert to authenticated
  with check (user_id = auth.uid ());

create policy "ue_update" on public.user_equipment for update to authenticated
  using (user_id = auth.uid ())
  with check (user_id = auth.uid ());

create policy "ue_delete" on public.user_equipment for delete to authenticated
  using (user_id = auth.uid ());

-- ---------------------------------------------------------------------------
-- Meal plans
-- ---------------------------------------------------------------------------
create policy "mp_select" on public.meal_plans for select to authenticated
  using (owner_id = auth.uid ());

create policy "mp_insert" on public.meal_plans for insert to authenticated
  with check (owner_id = auth.uid () or owner_id is null);

create policy "mp_update" on public.meal_plans for update to authenticated
  using (owner_id = auth.uid ())
  with check (owner_id = auth.uid ());

create policy "mp_delete" on public.meal_plans for delete to authenticated
  using (owner_id = auth.uid ());

create policy "mpe_select" on public.meal_plan_entries for select to authenticated
  using (
    exists (
      select 1
      from public.meal_plans p
      where p.id = meal_plan_entries.meal_plan_id
        and p.owner_id = auth.uid ()
    )
  );

create policy "mpe_insert" on public.meal_plan_entries for insert to authenticated
  with check (
    exists (
      select 1
      from public.meal_plans p
      where p.id = meal_plan_entries.meal_plan_id
        and p.owner_id = auth.uid ()
    )
  );

create policy "mpe_update" on public.meal_plan_entries for update to authenticated
  using (
    exists (
      select 1
      from public.meal_plans p
      where p.id = meal_plan_entries.meal_plan_id
        and p.owner_id = auth.uid ()
    )
  )
  with check (
    exists (
      select 1
      from public.meal_plans p
      where p.id = meal_plan_entries.meal_plan_id
        and p.owner_id = auth.uid ()
    )
  );

create policy "mpe_delete" on public.meal_plan_entries for delete to authenticated
  using (
    exists (
      select 1
      from public.meal_plans p
      where p.id = meal_plan_entries.meal_plan_id
        and p.owner_id = auth.uid ()
    )
  );

-- ---------------------------------------------------------------------------
-- Storage: allow authenticated uploads to recipe-images (adjust bucket name if different)
-- ---------------------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('recipe-images', 'recipe-images', true)
on conflict (id) do nothing;

drop policy if exists "recipe_images_public_read" on storage.objects;
create policy "recipe_images_public_read" on storage.objects for select
  using (bucket_id = 'recipe-images');

drop policy if exists "recipe_images_auth_insert" on storage.objects;
create policy "recipe_images_auth_insert" on storage.objects for insert to authenticated
  with check (bucket_id = 'recipe-images');

drop policy if exists "recipe_images_auth_update" on storage.objects;
create policy "recipe_images_auth_update" on storage.objects for update to authenticated
  using (bucket_id = 'recipe-images')
  with check (bucket_id = 'recipe-images');

drop policy if exists "recipe_images_auth_delete" on storage.objects;
create policy "recipe_images_auth_delete" on storage.objects for delete to authenticated
  using (bucket_id = 'recipe-images');
