-- Preferred products per ingredient.
--
-- Each row is a ranked product that can satisfy a generic ingredient (e.g.
-- "Baking Powder" -> [Rumford, Bob's Red Mill, Generic]). Purely a
-- preference list surfaced in the inventory side sheet; it does NOT create
-- extra inventory rows or sub-ingredients.
--
-- Safe to re-run (idempotent). Paste the whole file into the Supabase SQL
-- editor: New query -> Run as role postgres on Primary.

create table if not exists public.ingredient_products (
  id bigint generated by default as identity primary key,
  ingredient_id bigint not null references public.ingredients (id) on delete cascade,
  owner_id uuid references auth.users (id) on delete cascade,
  rank integer not null default 0,
  name text not null,
  brand text,
  url text,
  barcode text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists ingredient_products_ingredient_idx
  on public.ingredient_products (ingredient_id, rank);

create index if not exists ingredient_products_owner_idx
  on public.ingredient_products (owner_id);

-- Stamp owner_id on insert using the shared helper that the other tables use.
drop trigger if exists kitchenos_ingredient_products_owner
  on public.ingredient_products;
create trigger kitchenos_ingredient_products_owner
  before insert on public.ingredient_products
  for each row
  execute function public.kitchenos_set_owner_id();

-- Keep updated_at fresh.
create or replace function public.ingredient_products_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists ingredient_products_touch_updated_at
  on public.ingredient_products;
create trigger ingredient_products_touch_updated_at
  before update on public.ingredient_products
  for each row
  execute function public.ingredient_products_touch_updated_at();

alter table public.ingredient_products enable row level security;

drop policy if exists "ingredient_products_select_own" on public.ingredient_products;
create policy "ingredient_products_select_own" on public.ingredient_products
  for select to authenticated
  using (owner_id = auth.uid ());

drop policy if exists "ingredient_products_insert_own" on public.ingredient_products;
create policy "ingredient_products_insert_own" on public.ingredient_products
  for insert to authenticated
  with check (owner_id = auth.uid () or owner_id is null);

drop policy if exists "ingredient_products_update_own" on public.ingredient_products;
create policy "ingredient_products_update_own" on public.ingredient_products
  for update to authenticated
  using (owner_id = auth.uid ())
  with check (owner_id = auth.uid ());

drop policy if exists "ingredient_products_delete_own" on public.ingredient_products;
create policy "ingredient_products_delete_own" on public.ingredient_products
  for delete to authenticated
  using (owner_id = auth.uid ());
