-- Run this in Supabase SQL Editor
create table if not exists public.recipes (
  id bigint generated by default as identity primary key,
  name text not null,
  image_url text,
  image_urls jsonb,
  notes text,
  ingredients text,
  instructions text,
  source_url text,
  servings integer,
  prep_time_minutes integer,
  cook_time_minutes integer,
  total_time_minutes integer,
  calories integer,
  protein_grams integer,
  fat_grams integer,
  carbs_grams integer,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.ingredients (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.recipe_ingredients (
  recipe_id bigint not null references public.recipes(id) on delete cascade,
  ingredient_id bigint not null references public.ingredients(id) on delete cascade,
  created_at timestamptz default now(),
  primary key (recipe_id, ingredient_id)
);

alter table public.recipes enable row level security;
alter table public.ingredients enable row level security;
alter table public.recipe_ingredients enable row level security;

drop policy if exists "Public read recipes" on public.recipes;
create policy "Public read recipes"
  on public.recipes
  for select
  using (true);

drop policy if exists "Public write recipes" on public.recipes;
create policy "Public write recipes"
  on public.recipes
  for insert
  with check (true);

drop policy if exists "Public update recipes" on public.recipes;
create policy "Public update recipes"
  on public.recipes
  for update
  using (true)
  with check (true);

drop policy if exists "Public delete recipes" on public.recipes;
create policy "Public delete recipes"
  on public.recipes
  for delete
  using (true);

drop policy if exists "Public read ingredients" on public.ingredients;
create policy "Public read ingredients"
  on public.ingredients
  for select
  using (true);

drop policy if exists "Public write ingredients" on public.ingredients;
create policy "Public write ingredients"
  on public.ingredients
  for insert
  with check (true);

drop policy if exists "Public update ingredients" on public.ingredients;
create policy "Public update ingredients"
  on public.ingredients
  for update
  using (true)
  with check (true);

drop policy if exists "Public delete ingredients" on public.ingredients;
create policy "Public delete ingredients"
  on public.ingredients
  for delete
  using (true);

drop policy if exists "Public read recipe ingredients" on public.recipe_ingredients;
create policy "Public read recipe ingredients"
  on public.recipe_ingredients
  for select
  using (true);

drop policy if exists "Public write recipe ingredients" on public.recipe_ingredients;
create policy "Public write recipe ingredients"
  on public.recipe_ingredients
  for insert
  with check (true);

drop policy if exists "Public delete recipe ingredients" on public.recipe_ingredients;
create policy "Public delete recipe ingredients"
  on public.recipe_ingredients
  for delete
  using (true);

-- If you added identity to an existing table with data, run:
-- \i app/database/supabase_fix_identity.sql
