-- One-time KitchenOS inventory unit cleanup.

-- Generated from an approved review file. Re-run only if these IDs still match the intended rows.

begin;

-- Approved inventory_items.unit updates: 273
with updates(id, unit) as (
  values
  (1, 'head'::text),
  (3, 'ea'::text),
  (4, 'ea'::text),
  (5, 'piece'::text),
  (6, 'count'::text),
  (7, 'bunch'::text),
  (8, 'bunch'::text),
  (9, 'head'::text),
  (10, 'bag'::text),
  (11, 'head'::text),
  (12, 'bunch'::text),
  (13, 'lb'::text),
  (14, 'pkg'::text),
  (15, 'count'::text),
  (16, 'count'::text),
  (17, 'lb'::text),
  (18, 'ea'::text),
  (19, 'bunch'::text),
  (21, 'pkg'::text),
  (22, 'pkg'::text),
  (23, 'container'::text),
  (24, 'head'::text),
  (25, 'head'::text),
  (26, 'pkg'::text),
  (27, 'bag'::text),
  (28, 'container'::text),
  (29, 'bunch'::text),
  (30, 'bag'::text),
  (31, 'count'::text),
  (135, 'bottle'::text),
  (136, 'bottle'::text),
  (137, 'box'::text),
  (138, 'jar'::text),
  (139, 'jar'::text),
  (140, 'container'::text),
  (141, 'jar'::text),
  (142, 'container'::text),
  (143, 'bottle'::text),
  (144, 'jar'::text),
  (145, 'bottle'::text),
  (183, 'bottle'::text),
  (184, 'jar'::text),
  (185, 'dozen'::text),
  (186, 'container'::text),
  (187, 'bag'::text),
  (188, 'bottle'::text),
  (189, 'ea'::text),
  (190, 'container'::text),
  (191, 'bag'::text),
  (192, 'bottle'::text),
  (193, 'can'::text),
  (194, 'tub'::text),
  (195, 'container'::text),
  (196, 'ea'::text),
  (197, 'count'::text),
  (198, 'container'::text),
  (199, 'bag'::text),
  (200, 'box'::text),
  (201, 'can'::text),
  (202, 'container'::text),
  (203, 'bottle'::text),
  (204, 'can'::text),
  (205, 'bottle'::text),
  (206, 'container'::text),
  (207, 'bag'::text),
  (208, 'bottle'::text),
  (209, 'ea'::text),
  (210, 'block'::text),
  (213, 'bottle'::text),
  (214, 'block'::text),
  (215, 'block'::text),
  (218, 'pkg'::text),
  (220, 'bag'::text),
  (221, 'bag'::text),
  (222, 'bunch'::text),
  (223, 'bunch'::text),
  (225, 'pkg'::text),
  (226, 'pkg'::text),
  (227, 'ea'::text),
  (228, 'pkg'::text),
  (229, 'pkg'::text),
  (231, 'dozen'::text),
  (233, 'container'::text),
  (234, 'bottle'::text),
  (235, 'bottle'::text),
  (236, 'block'::text),
  (237, 'tub'::text),
  (240, 'tub'::text),
  (241, 'tub'::text),
  (242, 'bag'::text),
  (243, 'bag'::text),
  (244, 'bag'::text),
  (245, 'bag'::text),
  (246, 'bag'::text),
  (247, 'bag'::text),
  (248, 'bag'::text),
  (249, 'bag'::text),
  (250, 'bottle'::text),
  (251, 'bottle'::text),
  (252, 'bottle'::text),
  (253, 'pkg'::text),
  (254, 'bunch'::text),
  (255, 'jar'::text),
  (256, 'box'::text),
  (257, 'tub'::text),
  (258, 'bunch'::text),
  (259, 'bottle'::text),
  (260, 'bottle'::text),
  (261, 'bottle'::text),
  (262, 'bottle'::text),
  (263, 'box'::text),
  (264, 'box'::text),
  (265, 'box'::text),
  (266, 'box'::text),
  (267, 'box'::text),
  (268, 'pkg'::text),
  (269, 'box'::text),
  (270, 'box'::text),
  (271, 'box'::text),
  (272, 'container'::text),
  (273, 'can'::text),
  (274, 'ea'::text),
  (275, 'ea'::text),
  (276, 'ea'::text),
  (277, 'bag'::text),
  (299, 'container'::text),
  (300, 'jar'::text),
  (301, 'box'::text),
  (302, 'box'::text),
  (303, 'pkg'::text),
  (304, 'ea'::text),
  (305, 'can'::text),
  (306, 'tub'::text),
  (307, 'container'::text),
  (308, 'jar'::text),
  (309, 'block'::text),
  (310, 'bottle'::text),
  (311, 'jar'::text),
  (312, 'jar'::text),
  (313, 'jar'::text),
  (314, 'count'::text),
  (315, 'bag'::text),
  (316, 'jar'::text),
  (317, 'ea'::text),
  (318, 'bag'::text),
  (319, 'ea'::text),
  (320, 'jar'::text),
  (321, 'can'::text),
  (322, 'bag'::text),
  (323, 'bottle'::text),
  (324, 'bottle'::text),
  (325, 'bottle'::text),
  (326, 'bottle'::text),
  (327, 'bottle'::text),
  (328, 'jar'::text),
  (329, 'bag'::text),
  (330, 'box'::text),
  (331, 'jar'::text),
  (332, 'bag'::text),
  (333, 'bag'::text),
  (334, 'jar'::text),
  (335, 'bottle'::text),
  (336, 'bag'::text),
  (337, 'bag'::text),
  (338, 'bag'::text),
  (339, 'bag'::text),
  (340, 'ea'::text),
  (341, 'bag'::text),
  (342, 'bag'::text),
  (343, 'bag'::text),
  (344, 'container'::text),
  (345, 'jar'::text),
  (346, 'bottle'::text),
  (347, 'box'::text),
  (348, 'container'::text),
  (349, 'jar'::text),
  (350, 'ea'::text),
  (351, 'bag'::text),
  (352, 'ea'::text),
  (353, 'bag'::text),
  (354, 'jar'::text),
  (355, 'bag'::text),
  (356, 'container'::text),
  (357, 'lb'::text),
  (358, 'box'::text),
  (359, 'jar'::text),
  (360, 'bag'::text),
  (361, 'piece'::text),
  (362, 'bottle'::text),
  (363, 'jar'::text),
  (364, 'box'::text),
  (365, 'jar'::text),
  (366, 'bag'::text),
  (367, 'jar'::text),
  (368, 'bag'::text),
  (369, 'bag'::text),
  (370, 'bottle'::text),
  (371, 'bottle'::text),
  (372, 'bag'::text),
  (373, 'bag'::text),
  (374, 'pkg'::text),
  (375, 'head'::text),
  (376, 'bag'::text),
  (377, 'jar'::text),
  (378, 'container'::text),
  (379, 'bunch'::text),
  (380, 'pkg'::text),
  (383, 'bag'::text),
  (384, 'container'::text),
  (385, 'container'::text),
  (386, 'bottle'::text),
  (387, 'jar'::text),
  (388, 'bottle'::text),
  (389, 'bag'::text),
  (390, 'container'::text),
  (391, 'pkg'::text),
  (392, 'block'::text),
  (393, 'bag'::text),
  (394, 'bottle'::text),
  (395, 'bottle'::text),
  (396, 'bag'::text),
  (398, 'jar'::text),
  (399, 'jar'::text),
  (400, 'can'::text),
  (401, 'bunch'::text),
  (402, 'tub'::text),
  (403, 'can'::text),
  (404, 'bag'::text),
  (405, 'bag'::text),
  (406, 'bag'::text),
  (407, 'bag'::text),
  (408, 'whole'::text),
  (409, 'tub'::text),
  (410, 'jar'::text),
  (411, 'jar'::text),
  (412, 'jar'::text),
  (413, 'jar'::text),
  (414, 'box'::text),
  (415, 'jar'::text),
  (416, 'jar'::text),
  (417, 'bottle'::text),
  (418, 'jar'::text),
  (419, 'bag'::text),
  (420, 'bag'::text),
  (421, 'slice'::text),
  (422, 'piece'::text),
  (423, 'ea'::text),
  (424, 'head'::text),
  (425, 'block'::text),
  (426, 'bottle'::text),
  (427, 'jar'::text),
  (428, 'bag'::text),
  (429, 'bag'::text),
  (430, 'tub'::text),
  (431, 'bag'::text),
  (432, 'pkg'::text),
  (433, 'block'::text),
  (434, 'bag'::text),
  (435, 'bag'::text),
  (436, 'bunch'::text),
  (437, 'bag'::text),
  (438, 'bottle'::text),
  (439, 'lb'::text),
  (440, 'count'::text),
  (441, 'ea'::text),
  (442, 'ea'::text),
  (443, 'box'::text),
  (444, 'lb'::text),
  (445, 'pkg'::text),
  (446, 'bag'::text),
  (447, 'bag'::text),
  (448, 'head'::text),
  (449, 'bag'::text)
)
update public.inventory_items as target
set unit = updates.unit,
    updated_at = now()
from updates
where target.id = updates.id;

-- Approved inventory_items.recipe_unit updates: 273
with updates(id, recipe_unit) as (
  values
  (1, 'clove'::text),
  (3, 'whole'::text),
  (4, 'whole'::text),
  (5, 'g'::text),
  (6, 'ea'::text),
  (7, 'ea'::text),
  (8, 'cup'::text),
  (9, 'cup'::text),
  (10, 'cup'::text),
  (11, 'cup'::text),
  (12, 'cup'::text),
  (13, 'piece'::text),
  (14, 'g'::text),
  (15, 'ea'::text),
  (16, 'ea'::text),
  (17, 'lb'::text),
  (18, 'ea'::text),
  (19, 'cup'::text),
  (21, 'cup'::text),
  (22, 'g'::text),
  (23, 'cup'::text),
  (24, 'cup'::text),
  (25, 'cup'::text),
  (26, 'oz'::text),
  (27, 'cup'::text),
  (28, 'cup'::text),
  (29, 'sprig'::text),
  (30, 'count'::text),
  (31, 'whole'::text),
  (135, 'tbsp'::text),
  (136, 'tbsp'::text),
  (137, 'tbsp'::text),
  (138, 'tsp'::text),
  (139, 'tsp'::text),
  (140, 'tsp'::text),
  (141, 'tsp'::text),
  (142, 'tsp'::text),
  (143, 'tbsp'::text),
  (144, 'tbsp'::text),
  (145, 'tsp'::text),
  (183, 'cup'::text),
  (184, 'tsp'::text),
  (185, 'ea'::text),
  (186, 'ml'::text),
  (187, 'g'::text),
  (188, 'tsp'::text),
  (189, 'ea'::text),
  (190, 'ea'::text),
  (191, 'cup'::text),
  (192, 'tbsp'::text),
  (193, 'tsp'::text),
  (194, 'cup'::text),
  (195, 'cup'::text),
  (196, 'ea'::text),
  (197, 'count'::text),
  (198, 'ml'::text),
  (199, 'g'::text),
  (200, 'tbsp'::text),
  (201, 'tsp'::text),
  (202, 'tsp'::text),
  (203, 'tsp'::text),
  (204, 'tsp'::text),
  (205, 'cup'::text),
  (206, 'ea'::text),
  (207, 'cup'::text),
  (208, 'tbsp'::text),
  (209, 'ea'::text),
  (210, 'tbsp'::text),
  (213, 'ml'::text),
  (214, 'tbsp'::text),
  (215, 'tbsp'::text),
  (218, 'g'::text),
  (220, 'cup'::text),
  (221, 'cup'::text),
  (222, 'cup'::text),
  (223, 'cup'::text),
  (225, 'oz'::text),
  (226, 'oz'::text),
  (227, 'g'::text),
  (228, 'g'::text),
  (229, 'g'::text),
  (231, 'count'::text),
  (233, 'cup'::text),
  (234, 'tbsp'::text),
  (235, 'tbsp'::text),
  (236, 'g'::text),
  (237, 'g'::text),
  (240, 'cup'::text),
  (241, 'cup'::text),
  (242, 'cup'::text),
  (243, 'cup'::text),
  (244, 'cup'::text),
  (245, 'cup'::text),
  (246, 'cup'::text),
  (247, 'cup'::text),
  (248, 'cup'::text),
  (249, 'cup'::text),
  (250, 'tbsp'::text),
  (251, 'cup'::text),
  (252, 'cup'::text),
  (253, 'g'::text),
  (254, 'bunch'::text),
  (255, 'tsp'::text),
  (256, 'cup'::text),
  (257, 'tbsp'::text),
  (258, 'ea'::text),
  (259, 'tsp'::text),
  (260, 'tsp'::text),
  (261, 'tbsp'::text),
  (262, 'tbsp'::text),
  (263, 'g'::text),
  (264, 'g'::text),
  (265, 'g'::text),
  (266, 'g'::text),
  (267, 'g'::text),
  (268, 'g'::text),
  (269, 'g'::text),
  (270, 'g'::text),
  (271, 'g'::text),
  (272, 'cup'::text),
  (273, 'ml'::text),
  (274, 'ea'::text),
  (275, 'ea'::text),
  (276, 'whole'::text),
  (277, 'cup'::text),
  (299, 'tsp'::text),
  (300, 'tsp'::text),
  (301, 'tsp'::text),
  (302, 'g'::text),
  (303, 'lb'::text),
  (304, 'cup'::text),
  (305, 'tbsp'::text),
  (306, 'cup'::text),
  (307, 'cup'::text),
  (308, 'tsp'::text),
  (309, 'cup'::text),
  (310, 'tbsp'::text),
  (311, 'tbsp'::text),
  (312, 'tsp'::text),
  (313, 'tsp'::text),
  (314, 'whole'::text),
  (315, 'lb'::text),
  (316, 'tsp'::text),
  (317, 'ea'::text),
  (318, 'cup'::text),
  (319, 'ea'::text),
  (320, 'tsp'::text),
  (321, 'cup'::text),
  (322, 'cup'::text),
  (323, 'cup'::text),
  (324, 'oz'::text),
  (325, 'oz'::text),
  (326, 'ml'::text),
  (327, 'tbsp'::text),
  (328, 'ml'::text),
  (329, 'piece'::text),
  (330, 'piece'::text),
  (331, 'tbsp'::text),
  (332, 'tbsp'::text),
  (333, 'tbsp'::text),
  (334, 'tsp'::text),
  (335, 'tbsp'::text),
  (336, 'cup'::text),
  (337, 'cup'::text),
  (338, 'cup'::text),
  (339, 'lb'::text),
  (340, 'ea'::text),
  (341, 'lb'::text),
  (342, 'g'::text),
  (343, 'g'::text),
  (344, 'tsp'::text),
  (345, 'tbsp'::text),
  (346, 'tbsp'::text),
  (347, 'tsp'::text),
  (348, 'cup'::text),
  (349, 'tsp'::text),
  (350, 'tsp'::text),
  (351, 'cup'::text),
  (352, 'ea'::text),
  (353, 'tbsp'::text),
  (354, 'tbsp'::text),
  (355, 'tbsp'::text),
  (356, 'cup'::text),
  (357, 'lb'::text),
  (358, 'cup'::text),
  (359, 'whole'::text),
  (360, 'cup'::text),
  (361, 'piece'::text),
  (362, 'cup'::text),
  (363, 'tbsp'::text),
  (364, 'g'::text),
  (365, 'g'::text),
  (366, 'cup'::text),
  (367, 'tbsp'::text),
  (368, 'tsp'::text),
  (369, 'tbsp'::text),
  (370, 'tbsp'::text),
  (371, 'tbsp'::text),
  (372, 'tbsp'::text),
  (373, 'tbsp'::text),
  (374, 'g'::text),
  (375, 'cup'::text),
  (376, 'cup'::text),
  (377, 'cup'::text),
  (378, 'cup'::text),
  (379, 'sprig'::text),
  (380, 'piece'::text),
  (383, 'cup'::text),
  (384, 'cup'::text),
  (385, 'ea'::text),
  (386, 'tbsp'::text),
  (387, 'tsp'::text),
  (388, 'tbsp'::text),
  (389, 'cup'::text),
  (390, 'cup'::text),
  (391, 'piece'::text),
  (392, 'g'::text),
  (393, 'cup'::text),
  (394, 'tbsp'::text),
  (395, 'tsp'::text),
  (396, 'cup'::text),
  (398, 'tsp'::text),
  (399, 'tsp'::text),
  (400, 'can'::text),
  (401, 'tbsp'::text),
  (402, 'g'::text),
  (403, 'ml'::text),
  (404, 'tbsp'::text),
  (405, 'cup'::text),
  (406, 'cup'::text),
  (407, 'tbsp'::text),
  (408, 'cup'::text),
  (409, 'cup'::text),
  (410, 'tbsp'::text),
  (411, 'tsp'::text),
  (412, 'tsp'::text),
  (413, 'tsp'::text),
  (414, 'bag'::text),
  (415, 'tbsp'::text),
  (416, 'tbsp'::text),
  (417, 'tbsp'::text),
  (418, 'tbsp'::text),
  (419, 'cup'::text),
  (420, 'cup'::text),
  (421, 'slice'::text),
  (422, 'g'::text),
  (423, 'whole'::text),
  (424, 'cup'::text),
  (425, 'g'::text),
  (426, 'tbsp'::text),
  (427, 'tsp'::text),
  (428, 'ea'::text),
  (429, 'slice'::text),
  (430, 'tbsp'::text),
  (431, 'cup'::text),
  (432, 'g'::text),
  (433, 'g'::text),
  (434, 'piece'::text),
  (435, 'g'::text),
  (436, 'cup'::text),
  (437, 'cup'::text),
  (438, 'tbsp'::text),
  (439, 'lb'::text),
  (440, 'ea'::text),
  (441, 'cup'::text),
  (442, 'cup'::text),
  (443, 'piece'::text),
  (444, 'g'::text),
  (445, 'ml'::text),
  (446, 'cup'::text),
  (447, 'g'::text),
  (448, 'cup'::text),
  (449, 'cup'::text)
)
update public.inventory_items as target
set recipe_unit = updates.recipe_unit,
    updated_at = now()
from updates
where target.id = updates.id;

-- Approved inventory_items.storage_location updates: 273
with updates(id, storage_location) as (
  values
  (1, 'Shallow Pantry'::text),
  (3, 'Shallow Pantry'::text),
  (4, 'Shallow Pantry'::text),
  (5, 'Fridge'::text),
  (6, 'Shallow Pantry'::text),
  (7, 'Shallow Pantry'::text),
  (8, 'Fridge'::text),
  (9, 'Fridge'::text),
  (10, 'Fridge'::text),
  (11, 'Fridge'::text),
  (12, 'Fridge'::text),
  (13, 'Fridge'::text),
  (14, 'Fridge'::text),
  (15, 'Fridge'::text),
  (16, 'Fridge'::text),
  (17, 'Fridge'::text),
  (18, 'Fridge'::text),
  (19, 'Fridge'::text),
  (21, 'Fridge'::text),
  (22, 'Fridge'::text),
  (23, 'Fridge'::text),
  (24, 'Fridge'::text),
  (25, 'Fridge'::text),
  (26, 'Fridge'::text),
  (27, 'Fridge'::text),
  (28, 'Fridge'::text),
  (29, 'Fridge'::text),
  (30, 'Fridge'::text),
  (31, 'Fridge'::text),
  (135, 'Fridge'::text),
  (136, 'Shallow Pantry'::text),
  (137, 'Shallow Pantry'::text),
  (138, 'Shallow Pantry'::text),
  (139, 'Shallow Pantry'::text),
  (140, 'Shallow Pantry'::text),
  (141, 'Shallow Pantry'::text),
  (142, 'Shallow Pantry'::text),
  (143, 'Shallow Pantry'::text),
  (144, 'Shallow Pantry'::text),
  (145, 'Shallow Pantry'::text),
  (183, 'Shallow Pantry'::text),
  (184, 'Fridge'::text),
  (185, 'Fridge'::text),
  (186, 'Fridge'::text),
  (187, 'Shallow Pantry'::text),
  (188, 'Shallow Pantry'::text),
  (189, 'Fridge'::text),
  (190, 'Fridge'::text),
  (191, 'Shallow Pantry'::text),
  (192, 'Fridge'::text),
  (193, 'Shallow Pantry'::text),
  (194, 'Fridge'::text),
  (195, 'Fridge'::text),
  (196, 'Shallow Pantry'::text),
  (197, 'Fridge'::text),
  (198, 'Fridge'::text),
  (199, 'Shallow Pantry'::text),
  (200, 'Shallow Pantry'::text),
  (201, 'Shallow Pantry'::text),
  (202, 'Shallow Pantry'::text),
  (203, 'Shallow Pantry'::text),
  (204, 'Shallow Pantry'::text),
  (205, 'Shallow Pantry'::text),
  (206, 'Fridge'::text),
  (207, 'Shallow Pantry'::text),
  (208, 'Fridge'::text),
  (209, 'Shallow Pantry'::text),
  (210, 'Fridge'::text),
  (213, 'Shallow Pantry'::text),
  (214, 'Fridge'::text),
  (215, 'Fridge'::text),
  (218, 'Fridge'::text),
  (220, 'Shallow Pantry'::text),
  (221, 'Shallow Pantry'::text),
  (222, 'Fridge'::text),
  (223, 'Fridge'::text),
  (225, 'Fridge'::text),
  (226, 'Fridge'::text),
  (227, 'Fridge'::text),
  (228, 'Fridge'::text),
  (229, 'Fridge'::text),
  (231, 'Fridge'::text),
  (233, 'Fridge'::text),
  (234, 'Fridge'::text),
  (235, 'Fridge'::text),
  (236, 'Fridge'::text),
  (237, 'Fridge'::text),
  (240, 'Fridge'::text),
  (241, 'Fridge'::text),
  (242, 'Shallow Pantry'::text),
  (243, 'Shallow Pantry'::text),
  (244, 'Shallow Pantry'::text),
  (245, 'Shallow Pantry'::text),
  (246, 'Shallow Pantry'::text),
  (247, 'Shallow Pantry'::text),
  (248, 'Shallow Pantry'::text),
  (249, 'Shallow Pantry'::text),
  (250, 'Shallow Pantry'::text),
  (251, 'Shallow Pantry'::text),
  (252, 'Shallow Pantry'::text),
  (253, 'Shallow Pantry'::text),
  (254, 'Fridge'::text),
  (255, 'Shallow Pantry'::text),
  (256, 'Fridge'::text),
  (257, 'Fridge'::text),
  (258, 'Fridge'::text),
  (259, 'Shallow Pantry'::text),
  (260, 'Shallow Pantry'::text),
  (261, 'Shallow Pantry'::text),
  (262, 'Shallow Pantry'::text),
  (263, 'Shallow Pantry'::text),
  (264, 'Shallow Pantry'::text),
  (265, 'Shallow Pantry'::text),
  (266, 'Shallow Pantry'::text),
  (267, 'Shallow Pantry'::text),
  (268, 'Shallow Pantry'::text),
  (269, 'Shallow Pantry'::text),
  (270, 'Shallow Pantry'::text),
  (271, 'Shallow Pantry'::text),
  (272, 'Fridge'::text),
  (273, 'Shallow Pantry'::text),
  (274, 'Shallow Pantry'::text),
  (275, 'Shallow Pantry'::text),
  (276, 'Shallow Pantry'::text),
  (277, 'Shallow Pantry'::text),
  (299, 'Shallow Pantry'::text),
  (300, 'Shallow Pantry'::text),
  (301, 'Shallow Pantry'::text),
  (302, 'Shallow Pantry'::text),
  (303, 'Fridge'::text),
  (304, 'Shallow Pantry'::text),
  (305, 'Fridge'::text),
  (306, 'Fridge'::text),
  (307, 'Fridge'::text),
  (308, 'Shallow Pantry'::text),
  (309, 'Fridge'::text),
  (310, 'Shallow Pantry'::text),
  (311, 'Fridge'::text),
  (312, 'Shallow Pantry'::text),
  (313, 'Shallow Pantry'::text),
  (314, 'Shallow Pantry'::text),
  (315, 'Freezer'::text),
  (316, 'Shallow Pantry'::text),
  (317, 'Fridge'::text),
  (318, 'Shallow Pantry'::text),
  (319, 'Fridge'::text),
  (320, 'Shallow Pantry'::text),
  (321, 'Shallow Pantry'::text),
  (322, 'Shallow Pantry'::text),
  (323, 'Shallow Pantry'::text),
  (324, 'Shallow Pantry'::text),
  (325, 'Shallow Pantry'::text),
  (326, 'Fridge'::text),
  (327, 'Shallow Pantry'::text),
  (328, 'Fridge'::text),
  (329, 'Freezer'::text),
  (330, 'Shallow Pantry'::text),
  (331, 'Shallow Pantry'::text),
  (332, 'Shallow Pantry'::text),
  (333, 'Shallow Pantry'::text),
  (334, 'Shallow Pantry'::text),
  (335, 'Shallow Pantry'::text),
  (336, 'Shallow Pantry'::text),
  (337, 'Shallow Pantry'::text),
  (338, 'Shallow Pantry'::text),
  (339, 'Shallow Pantry'::text),
  (340, 'Shallow Pantry'::text),
  (341, 'Shallow Pantry'::text),
  (342, 'Shallow Pantry'::text),
  (343, 'Shallow Pantry'::text),
  (344, 'Shallow Pantry'::text),
  (345, 'Shallow Pantry'::text),
  (346, 'Fridge'::text),
  (347, 'Shallow Pantry'::text),
  (348, 'Freezer'::text),
  (349, 'Shallow Pantry'::text),
  (350, 'Fridge'::text),
  (351, 'Shallow Pantry'::text),
  (352, 'Shallow Pantry'::text),
  (353, 'Shallow Pantry'::text),
  (354, 'Shallow Pantry'::text),
  (355, 'Fridge'::text),
  (356, 'Fridge'::text),
  (357, 'Fridge'::text),
  (358, 'Fridge'::text),
  (359, 'Shallow Pantry'::text),
  (360, 'Fridge'::text),
  (361, 'Shallow Pantry'::text),
  (362, 'Shallow Pantry'::text),
  (363, 'Shallow Pantry'::text),
  (364, 'Shallow Pantry'::text),
  (365, 'Fridge'::text),
  (366, 'Shallow Pantry'::text),
  (367, 'Fridge'::text),
  (368, 'Shallow Pantry'::text),
  (369, 'Shallow Pantry'::text),
  (370, 'Fridge'::text),
  (371, 'Shallow Pantry'::text),
  (372, 'Shallow Pantry'::text),
  (373, 'Shallow Pantry'::text),
  (374, 'Shallow Pantry'::text),
  (375, 'Fridge'::text),
  (376, 'Freezer'::text),
  (377, 'Fridge'::text),
  (378, 'Fridge'::text),
  (379, 'Fridge'::text),
  (380, 'Fridge'::text),
  (383, 'Shallow Pantry'::text),
  (384, 'Shallow Pantry'::text),
  (385, 'Fridge'::text),
  (386, 'Fridge'::text),
  (387, 'Shallow Pantry'::text),
  (388, 'Shallow Pantry'::text),
  (389, 'Shallow Pantry'::text),
  (390, 'Fridge'::text),
  (391, 'Shallow Pantry'::text),
  (392, 'Fridge'::text),
  (393, 'Freezer'::text),
  (394, 'Shallow Pantry'::text),
  (395, 'Shallow Pantry'::text),
  (396, 'Freezer'::text),
  (398, 'Shallow Pantry'::text),
  (399, 'Shallow Pantry'::text),
  (400, 'Shallow Pantry'::text),
  (401, 'Fridge'::text),
  (402, 'Fridge'::text),
  (403, 'Fridge'::text),
  (404, 'Shallow Pantry'::text),
  (405, 'Shallow Pantry'::text),
  (406, 'Shallow Pantry'::text),
  (407, 'Shallow Pantry'::text),
  (408, 'Shallow Pantry'::text),
  (409, 'Fridge'::text),
  (410, 'Shallow Pantry'::text),
  (411, 'Shallow Pantry'::text),
  (412, 'Shallow Pantry'::text),
  (413, 'Shallow Pantry'::text),
  (414, 'Shallow Pantry'::text),
  (415, 'Shallow Pantry'::text),
  (416, 'Fridge'::text),
  (417, 'Shallow Pantry'::text),
  (418, 'Fridge'::text),
  (419, 'Fridge'::text),
  (420, 'Shallow Pantry'::text),
  (421, 'Shallow Pantry'::text),
  (422, 'Fridge'::text),
  (423, 'Shallow Pantry'::text),
  (424, 'Fridge'::text),
  (425, 'Fridge'::text),
  (426, 'Shallow Pantry'::text),
  (427, 'Shallow Pantry'::text),
  (428, 'Shallow Pantry'::text),
  (429, 'Shallow Pantry'::text),
  (430, 'Fridge'::text),
  (431, 'Shallow Pantry'::text),
  (432, 'Fridge'::text),
  (433, 'Fridge'::text),
  (434, 'Shallow Pantry'::text),
  (435, 'Shallow Pantry'::text),
  (436, 'Fridge'::text),
  (437, 'Shallow Pantry'::text),
  (438, 'Shallow Pantry'::text),
  (439, 'Fridge'::text),
  (440, 'Shallow Pantry'::text),
  (441, 'Shallow Pantry'::text),
  (442, 'Fridge'::text),
  (443, 'Freezer'::text),
  (444, 'Shallow Pantry'::text),
  (445, 'Shallow Pantry'::text),
  (446, 'Shallow Pantry'::text),
  (447, 'Shallow Pantry'::text),
  (448, 'Fridge'::text),
  (449, 'Shallow Pantry'::text)
)
update public.inventory_items as target
set storage_location = updates.storage_location,
    updated_at = now()
from updates
where target.id = updates.id;

-- Approved ingredient_products unit-size updates: 120
with updates(
  id,
  unit_size_amount,
  unit_size_unit
) as (
  values
  (1, 1::numeric, 'kg'::text),
  (2, 500::numeric, 'g'::text),
  (3, 64::numeric, 'fl oz'::text),
  (4, 1::numeric, 'count'::text),
  (5, 296::numeric, 'ml'::text),
  (6, 225::numeric, 'g'::text),
  (7, 473::numeric, 'ml'::text),
  (8, null::numeric, null::text),
  (9, 1::numeric, 'count'::text),
  (10, 750::numeric, 'g'::text),
  (12, null::numeric, null::text),
  (13, 64::numeric, 'fl oz'::text),
  (14, 6::numeric, 'oz'::text),
  (16, 1.5::numeric, 'lb'::text),
  (17, 350::numeric, 'g'::text),
  (18, 4::numeric, 'lb'::text),
  (19, 2::numeric, 'count'::text),
  (20, 500::numeric, 'g'::text),
  (21, 24::numeric, 'oz'::text),
  (22, null::numeric, null::text),
  (23, 600::numeric, 'g'::text),
  (24, 30::numeric, 'g'::text),
  (25, 6::numeric, 'count'::text),
  (28, 135::numeric, 'g'::text),
  (29, null::numeric, null::text),
  (30, 250::numeric, 'g'::text),
  (31, 907::numeric, 'g'::text),
  (32, 907::numeric, 'g'::text),
  (33, 16::numeric, 'fl oz'::text),
  (34, 12::numeric, 'oz'::text),
  (35, 1::numeric, 'bunch'::text),
  (36, null::numeric, null::text),
  (37, 6::numeric, 'oz'::text),
  (38, 1::numeric, 'l'::text),
  (39, 24::numeric, 'count'::text),
  (40, 6::numeric, 'oz'::text),
  (41, 330::numeric, 'ml'::text),
  (44, 13.5::numeric, 'fl oz'::text),
  (45, 500::numeric, 'g'::text),
  (46, 75::numeric, 'g'::text),
  (47, 6::numeric, 'count'::text),
  (48, 2::numeric, 'lb'::text),
  (49, null::numeric, null::text),
  (50, 128::numeric, 'ml'::text),
  (51, null::numeric, null::text),
  (52, 2::numeric, 'lb'::text),
  (53, 450::numeric, 'g'::text),
  (54, 450::numeric, 'g'::text),
  (55, 16::numeric, 'fl oz'::text),
  (58, 1.5::numeric, 'lb'::text),
  (59, 24::numeric, 'count'::text),
  (60, 6::numeric, 'oz'::text),
  (61, 4::numeric, 'lb'::text),
  (62, 1.88::numeric, 'kg'::text),
  (63, 6::numeric, 'oz'::text),
  (64, 500::numeric, 'ml'::text),
  (65, 13.5::numeric, 'fl oz'::text),
  (66, 8::numeric, 'piece'::text),
  (68, 4::numeric, 'count'::text),
  (69, null::numeric, null::text),
  (70, 135::numeric, 'g'::text),
  (71, 128::numeric, 'ml'::text),
  (72, 4::numeric, 'lb'::text),
  (74, 4::numeric, 'fl oz'::text),
  (75, 24::numeric, 'oz'::text),
  (76, 312::numeric, 'g'::text),
  (77, 1::numeric, 'count'::text),
  (78, 14.5::numeric, 'oz'::text),
  (79, 4::numeric, 'oz'::text),
  (80, 33::numeric, 'g'::text),
  (81, 16::numeric, 'fl oz'::text),
  (82, 1::numeric, 'count'::text),
  (83, 6::numeric, 'oz'::text),
  (84, null::numeric, null::text),
  (85, 280::numeric, 'g'::text),
  (86, 1::numeric, 'bunch'::text),
  (87, null::numeric, null::text),
  (88, 1::numeric, 'count'::text),
  (89, 1::numeric, 'ea'::text),
  (90, null::numeric, null::text),
  (91, 1::numeric, 'bunch'::text),
  (92, 6::numeric, 'oz'::text),
  (93, null::numeric, null::text),
  (94, 269::numeric, 'g'::text),
  (95, null::numeric, null::text),
  (96, 1::numeric, 'bunch'::text),
  (97, 6::numeric, 'oz'::text),
  (98, null::numeric, null::text),
  (99, 1::numeric, 'count'::text),
  (100, 1::numeric, 'ea'::text),
  (101, 450::numeric, 'g'::text),
  (102, null::numeric, null::text),
  (103, 350::numeric, 'g'::text),
  (104, null::numeric, null::text),
  (105, null::numeric, null::text),
  (106, 1::numeric, 'count'::text),
  (107, 1::numeric, 'bunch'::text),
  (108, null::numeric, null::text),
  (109, 1::numeric, 'bunch'::text),
  (110, 1::numeric, 'count'::text),
  (111, 1::numeric, 'count'::text),
  (113, 227::numeric, 'g'::text),
  (115, 5::numeric, 'oz'::text),
  (116, 2::numeric, 'lb'::text),
  (117, null::numeric, null::text),
  (118, null::numeric, null::text),
  (121, null::numeric, null::text),
  (122, 1::numeric, 'head'::text),
  (123, 1::numeric, 'bunch'::text),
  (124, 1::numeric, 'head'::text),
  (126, 8::numeric, 'piece'::text),
  (127, null::numeric, null::text),
  (128, null::numeric, null::text),
  (129, 1::numeric, 'count'::text),
  (130, null::numeric, null::text),
  (131, null::numeric, null::text),
  (132, 1::numeric, 'bag'::text),
  (133, 1::numeric, 'bunch'::text),
  (134, 760::numeric, 'g'::text),
  (135, 128::numeric, 'ml'::text)
)
update public.ingredient_products as target
set unit_size_amount = updates.unit_size_amount,
    unit_size_unit = updates.unit_size_unit,
    updated_at = now()
from updates
where target.id = updates.id;

-- Approved ingredient_products price-basis updates: 120
with updates(
  id,
  price_basis,
  price_basis_amount,
  price_basis_unit
) as (
  values
  (1, 'package'::text, null::numeric, null::text),
  (2, 'package'::text, null::numeric, null::text),
  (3, 'package'::text, null::numeric, null::text),
  (4, 'unit'::text, 1::numeric, 'ea'::text),
  (5, 'package'::text, null::numeric, null::text),
  (6, 'package'::text, null::numeric, null::text),
  (7, 'package'::text, null::numeric, null::text),
  (8, 'package'::text, null::numeric, null::text),
  (9, 'unit'::text, 1::numeric, 'ea'::text),
  (10, 'package'::text, null::numeric, null::text),
  (12, 'package'::text, null::numeric, null::text),
  (13, 'package'::text, null::numeric, null::text),
  (14, 'package'::text, null::numeric, null::text),
  (16, 'package'::text, null::numeric, null::text),
  (17, 'package'::text, null::numeric, null::text),
  (18, 'package'::text, null::numeric, null::text),
  (19, 'package'::text, null::numeric, null::text),
  (20, 'package'::text, null::numeric, null::text),
  (21, 'package'::text, null::numeric, null::text),
  (22, 'package'::text, null::numeric, null::text),
  (23, 'package'::text, null::numeric, null::text),
  (24, 'package'::text, null::numeric, null::text),
  (25, 'package'::text, null::numeric, null::text),
  (28, 'package'::text, null::numeric, null::text),
  (29, 'package'::text, null::numeric, null::text),
  (30, 'package'::text, null::numeric, null::text),
  (31, 'package'::text, null::numeric, null::text),
  (32, 'package'::text, null::numeric, null::text),
  (33, 'package'::text, null::numeric, null::text),
  (34, 'package'::text, null::numeric, null::text),
  (35, 'unit'::text, 1::numeric, 'bunch'::text),
  (36, 'package'::text, null::numeric, null::text),
  (37, 'package'::text, null::numeric, null::text),
  (38, 'package'::text, null::numeric, null::text),
  (39, 'package'::text, null::numeric, null::text),
  (40, 'package'::text, null::numeric, null::text),
  (41, 'package'::text, null::numeric, null::text),
  (44, 'package'::text, null::numeric, null::text),
  (45, 'package'::text, null::numeric, null::text),
  (46, 'package'::text, null::numeric, null::text),
  (47, 'package'::text, null::numeric, null::text),
  (48, 'package'::text, null::numeric, null::text),
  (49, 'unit'::text, 1::numeric, 'ea'::text),
  (50, 'package'::text, null::numeric, null::text),
  (51, 'package'::text, null::numeric, null::text),
  (52, 'package'::text, null::numeric, null::text),
  (53, 'package'::text, null::numeric, null::text),
  (54, 'package'::text, null::numeric, null::text),
  (55, 'package'::text, null::numeric, null::text),
  (58, 'package'::text, null::numeric, null::text),
  (59, 'package'::text, null::numeric, null::text),
  (60, 'package'::text, null::numeric, null::text),
  (61, 'package'::text, null::numeric, null::text),
  (62, 'package'::text, null::numeric, null::text),
  (63, 'package'::text, null::numeric, null::text),
  (64, 'package'::text, null::numeric, null::text),
  (65, 'package'::text, null::numeric, null::text),
  (66, 'package'::text, null::numeric, null::text),
  (68, 'package'::text, null::numeric, null::text),
  (69, 'unit'::text, 1::numeric, 'ea'::text),
  (70, 'package'::text, null::numeric, null::text),
  (71, 'package'::text, null::numeric, null::text),
  (72, 'package'::text, null::numeric, null::text),
  (74, 'package'::text, null::numeric, null::text),
  (75, 'package'::text, null::numeric, null::text),
  (76, 'package'::text, null::numeric, null::text),
  (77, 'weight'::text, 1::numeric, 'kg'::text),
  (78, 'package'::text, null::numeric, null::text),
  (79, 'package'::text, null::numeric, null::text),
  (80, 'package'::text, null::numeric, null::text),
  (81, 'package'::text, null::numeric, null::text),
  (82, 'unit'::text, 1::numeric, 'ea'::text),
  (83, 'package'::text, null::numeric, null::text),
  (84, 'weight'::text, 1::numeric, 'kg'::text),
  (85, 'package'::text, null::numeric, null::text),
  (86, 'unit'::text, 1::numeric, 'ea'::text),
  (87, 'weight'::text, 1::numeric, 'kg'::text),
  (88, 'weight'::text, 1::numeric, 'kg'::text),
  (89, 'unit'::text, 1::numeric, 'ea'::text),
  (90, 'weight'::text, 1::numeric, 'kg'::text),
  (91, 'package'::text, null::numeric, null::text),
  (92, 'package'::text, null::numeric, null::text),
  (93, 'package'::text, null::numeric, null::text),
  (94, 'package'::text, null::numeric, null::text),
  (95, 'package'::text, null::numeric, null::text),
  (96, 'package'::text, null::numeric, null::text),
  (97, 'package'::text, null::numeric, null::text),
  (98, 'package'::text, null::numeric, null::text),
  (99, 'unit'::text, 1::numeric, 'ea'::text),
  (100, 'package'::text, null::numeric, null::text),
  (101, 'package'::text, null::numeric, null::text),
  (102, 'package'::text, null::numeric, null::text),
  (103, 'package'::text, null::numeric, null::text),
  (104, 'package'::text, null::numeric, null::text),
  (105, 'package'::text, null::numeric, null::text),
  (106, 'weight'::text, 1::numeric, 'kg'::text),
  (107, 'unit'::text, 1::numeric, 'bunch'::text),
  (108, 'weight'::text, 0.81::numeric, 'kg'::text),
  (109, 'package'::text, null::numeric, null::text),
  (110, 'package'::text, null::numeric, null::text),
  (111, 'package'::text, null::numeric, null::text),
  (113, 'package'::text, null::numeric, null::text),
  (115, 'package'::text, null::numeric, null::text),
  (116, 'package'::text, null::numeric, null::text),
  (117, 'weight'::text, 1::numeric, 'kg'::text),
  (118, 'weight'::text, 1::numeric, 'kg'::text),
  (121, 'weight'::text, 1::numeric, 'kg'::text),
  (122, 'unit'::text, 1::numeric, 'ea'::text),
  (123, 'unit'::text, 1::numeric, 'ea'::text),
  (124, 'unit'::text, 1::numeric, 'ea'::text),
  (126, 'package'::text, null::numeric, null::text),
  (127, 'weight'::text, 1::numeric, 'kg'::text),
  (128, 'package'::text, null::numeric, null::text),
  (129, 'unit'::text, 1::numeric, 'ea'::text),
  (130, 'unit'::text, 1::numeric, 'lb'::text),
  (131, 'package'::text, null::numeric, null::text),
  (132, 'package'::text, null::numeric, null::text),
  (133, 'package'::text, null::numeric, null::text),
  (134, 'package'::text, null::numeric, null::text),
  (135, 'package'::text, null::numeric, null::text)
)
update public.ingredient_products as target
set price_basis = updates.price_basis,
    price_basis_amount = updates.price_basis_amount,
    price_basis_unit = updates.price_basis_unit,
    updated_at = now()
from updates
where target.id = updates.id;

commit;
