-- Run this in Supabase SQL Editor
create table if not exists public.recipes (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  image_url text,
  image_urls jsonb,
  image_focus_y smallint,
  notes text,
  ingredients text,
  instructions text,
  source_url text,
  servings integer,
  prep_time_minutes integer,
  cook_time_minutes integer,
  total_time_minutes integer,
  calories integer,
  protein_grams integer,
  fat_grams integer,
  carbs_grams integer,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.ingredients (
  id bigint generated by default as identity primary key,
  name text not null unique,
  full_item_name text,
  full_item_name_alt text,
  current_stock text,
  minimum_stock text,
  maximum_stock text,
  category text,
  grocery_category text,
  price numeric,
  preferred_vendor text,
  brand_or_manufacturer text,
  notes text,
  ingredients_text text,
  food_type text default 'generic' check (food_type in ('generic', 'branded', 'custom')),
  barcode text,
  nutrition_fetched_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.ingredient_nutrients (
  ingredient_id bigint not null references public.ingredients(id) on delete cascade,
  nutrient_id   integer not null,
  nutrient_name text not null,
  value         real not null,
  unit          text not null,
  primary key (ingredient_id, nutrient_id)
);

create table if not exists public.ingredient_portions (
  id            bigint generated by default as identity primary key,
  ingredient_id bigint not null references public.ingredients(id) on delete cascade,
  gram_weight   real not null check (gram_weight > 0),
  description   text not null,
  source        text,
  is_default    boolean not null default false,
  created_at    timestamptz default now()
);

create table if not exists public.equipment (
  id bigint generated by default as identity primary key,
  name text not null unique,
  category text,
  has_item boolean not null default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

insert into public.equipment (name, category, has_item) values
  ('Chef''s knife', 'Knives and cutting', false),
  ('Paring knife', 'Knives and cutting', false),
  ('Serrated knife', 'Knives and cutting', false),
  ('Utility knife', 'Knives and cutting', false),
  ('Carving or slicing knife', 'Knives and cutting', false),
  ('Boning or fillet knife', 'Knives and cutting', false),
  ('Cleaver', 'Knives and cutting', false),
  ('Steak knives', 'Knives and cutting', false),
  ('Kitchen shears', 'Knives and cutting', false),
  ('Peeler', 'Knives and cutting', false),
  ('Grater or zester', 'Knives and cutting', false),
  ('Mandoline or slicer', 'Knives and cutting', false),
  ('Knife sharpener or honing steel', 'Knives and cutting', false),
  ('Cutting board', 'Knives and cutting', false),
  ('Bench scraper', 'Knives and cutting', false),
  ('Skillet or frying pan', 'Cookware', false),
  ('Saute pan', 'Cookware', false),
  ('Saucepan', 'Cookware', false),
  ('Stockpot', 'Cookware', false),
  ('Dutch oven or heavy pot', 'Cookware', false),
  ('Wok', 'Cookware', false),
  ('Grill pan or griddle', 'Cookware', false),
  ('Roasting pan', 'Cookware', false),
  ('Baking sheet (sheet pan)', 'Cookware', false),
  ('Steamer basket or insert', 'Cookware', false),
  ('Pressure cooker', 'Cookware', false),
  ('Slow cooker', 'Cookware', false),
  ('Rice cooker', 'Cookware', false),
  ('Mixing bowls', 'Bakeware and baking tools', false),
  ('Measuring cups and spoons', 'Bakeware and baking tools', false),
  ('Kitchen scale', 'Bakeware and baking tools', false),
  ('Whisk', 'Bakeware and baking tools', false),
  ('Spatula (silicone)', 'Bakeware and baking tools', false),
  ('Rolling pin', 'Bakeware and baking tools', false),
  ('Baking pans (cake, loaf, muffin, etc.)', 'Bakeware and baking tools', false),
  ('Pie or tart dish', 'Bakeware and baking tools', false),
  ('Cooling rack', 'Bakeware and baking tools', false),
  ('Oven thermometer', 'Bakeware and baking tools', false),
  ('Parchment paper and foil', 'Bakeware and baking tools', false),
  ('Storage wrap (plastic wrap or reusable wraps)', 'Bakeware and baking tools', false),
  ('Blender', 'Small appliances', false),
  ('Food processor', 'Small appliances', false),
  ('Stand or hand mixer', 'Small appliances', false),
  ('Immersion blender', 'Small appliances', false),
  ('Toaster', 'Small appliances', false),
  ('Toaster oven', 'Small appliances', false),
  ('Air fryer', 'Small appliances', false),
  ('Microwave', 'Small appliances', false),
  ('Electric kettle', 'Small appliances', false),
  ('Coffee maker', 'Small appliances', false),
  ('Coffee grinder', 'Small appliances', false),
  ('Espresso machine (optional)', 'Small appliances', false),
  ('Juicer (optional)', 'Small appliances', false),
  ('Waffle maker (optional)', 'Small appliances', false),
  ('Panini press or contact grill (optional)', 'Small appliances', false),
  ('Ice cream maker (optional)', 'Small appliances', false),
  ('Dehydrator (optional)', 'Small appliances', false),
  ('Vacuum sealer (optional)', 'Small appliances', false),
  ('Sous vide circulator (optional)', 'Small appliances', false),
  ('Can opener (electric or manual)', 'Small appliances', false),
  ('Refrigerator', 'Major appliances', false),
  ('Freezer', 'Major appliances', false),
  ('Range (cooktop + oven)', 'Major appliances', false),
  ('Oven (if separate)', 'Major appliances', false),
  ('Cooktop (if separate)', 'Major appliances', false),
  ('Vent hood', 'Major appliances', false),
  ('Dishwasher', 'Major appliances', false),
  ('Colander', 'Prep tools and utensils', false),
  ('Strainer (fine mesh)', 'Prep tools and utensils', false),
  ('Salad spinner', 'Prep tools and utensils', false),
  ('Garlic press', 'Prep tools and utensils', false),
  ('Citrus juicer', 'Prep tools and utensils', false),
  ('Can opener', 'Prep tools and utensils', false),
  ('Bottle opener / corkscrew', 'Prep tools and utensils', false),
  ('Funnel', 'Prep tools and utensils', false),
  ('Ladle', 'Prep tools and utensils', false),
  ('Tongs', 'Prep tools and utensils', false),
  ('Spoon set (solid + slotted)', 'Prep tools and utensils', false),
  ('Turner / spatula (flat)', 'Prep tools and utensils', false),
  ('Mixing spoon (wood or silicone)', 'Prep tools and utensils', false),
  ('Potato masher', 'Prep tools and utensils', false),
  ('Measuring pitcher', 'Prep tools and utensils', false),
  ('Kitchen timer', 'Prep tools and utensils', false),
  ('Instant-read thermometer', 'Prep tools and utensils', false),
  ('Kitchen torch (optional)', 'Prep tools and utensils', false),
  ('Food storage containers', 'Storage and organization', false),
  ('Pantry canisters', 'Storage and organization', false),
  ('Spice storage', 'Storage and organization', false),
  ('Labels or label maker', 'Storage and organization', false),
  ('Drawer organizers', 'Storage and organization', false),
  ('Pot lid organizer', 'Storage and organization', false),
  ('Trash can', 'Storage and organization', false),
  ('Compost bin (optional)', 'Storage and organization', false),
  ('Serving bowls and platters', 'Serving and table', false),
  ('Serving utensils', 'Serving and table', false),
  ('Salad bowl and servers', 'Serving and table', false),
  ('Cutting or serving board', 'Serving and table', false),
  ('Butter dish', 'Serving and table', false),
  ('Salt cellar / pepper mill', 'Serving and table', false),
  ('Dish rack or drying mat', 'Cleaning and safety', false),
  ('Dish brush / sponge', 'Cleaning and safety', false),
  ('Towels (dish + microfiber)', 'Cleaning and safety', false),
  ('Cleaning spray / dish soap', 'Cleaning and safety', false),
  ('Fire extinguisher', 'Cleaning and safety', false),
  ('First aid kit', 'Cleaning and safety', false),
  ('Smoke / CO detector', 'Cleaning and safety', false)
on conflict (name) do nothing;

create table if not exists public.shopping_items (
  id bigint generated by default as identity primary key,
  ingredient_id bigint references public.ingredients(id) on delete set null,
  name text not null,
  quantity text,
  unit text,
  store text,
  aisle text,
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.people (
  id bigint generated by default as identity primary key,
  name text not null,
  birth_date date,
  weight numeric,
  height text,
  daily_calorie_expenditure numeric,
  calorie_min numeric,
  calorie_max numeric,
  calorie_target numeric,
  protein_min_grams numeric,
  protein_max_grams numeric,
  protein_target_grams numeric,
  fat_min_grams numeric,
  fat_max_grams numeric,
  fat_target_grams numeric,
  carb_min_grams numeric,
  carb_max_grams numeric,
  carb_target_grams numeric,
  dietary_restrictions jsonb,
  allergies jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.recipe_ingredients (
  recipe_id bigint not null references public.recipes(id) on delete cascade,
  ingredient_id bigint not null references public.ingredients(id) on delete cascade,
  amount text,
  unit text,
  created_at timestamptz default now(),
  primary key (recipe_id, ingredient_id)
);

alter table public.recipes enable row level security;
alter table public.ingredients enable row level security;
alter table public.equipment enable row level security;
alter table public.shopping_items enable row level security;
alter table public.people enable row level security;
alter table public.recipe_ingredients enable row level security;

drop policy if exists "Public read recipes" on public.recipes;
create policy "Public read recipes"
  on public.recipes
  for select
  using (true);

drop policy if exists "Public write recipes" on public.recipes;
create policy "Public write recipes"
  on public.recipes
  for insert
  with check (true);

drop policy if exists "Public update recipes" on public.recipes;
create policy "Public update recipes"
  on public.recipes
  for update
  using (true)
  with check (true);

drop policy if exists "Public delete recipes" on public.recipes;
create policy "Public delete recipes"
  on public.recipes
  for delete
  using (true);

drop policy if exists "Public read ingredients" on public.ingredients;
create policy "Public read ingredients"
  on public.ingredients
  for select
  using (true);

drop policy if exists "Public write ingredients" on public.ingredients;
create policy "Public write ingredients"
  on public.ingredients
  for insert
  with check (true);

drop policy if exists "Public update ingredients" on public.ingredients;
create policy "Public update ingredients"
  on public.ingredients
  for update
  using (true)
  with check (true);

drop policy if exists "Public delete ingredients" on public.ingredients;
create policy "Public delete ingredients"
  on public.ingredients
  for delete
  using (true);

drop policy if exists "Public read equipment" on public.equipment;
create policy "Public read equipment"
  on public.equipment
  for select
  using (true);

drop policy if exists "Public write equipment" on public.equipment;
create policy "Public write equipment"
  on public.equipment
  for insert
  with check (true);

drop policy if exists "Public update equipment" on public.equipment;
create policy "Public update equipment"
  on public.equipment
  for update
  using (true)
  with check (true);

drop policy if exists "Public delete equipment" on public.equipment;
create policy "Public delete equipment"
  on public.equipment
  for delete
  using (true);

drop policy if exists "Public read shopping items" on public.shopping_items;
create policy "Public read shopping items"
  on public.shopping_items
  for select
  using (true);

drop policy if exists "Public write shopping items" on public.shopping_items;
create policy "Public write shopping items"
  on public.shopping_items
  for insert
  with check (true);

drop policy if exists "Public update shopping items" on public.shopping_items;
create policy "Public update shopping items"
  on public.shopping_items
  for update
  using (true)
  with check (true);

drop policy if exists "Public delete shopping items" on public.shopping_items;
create policy "Public delete shopping items"
  on public.shopping_items
  for delete
  using (true);

drop policy if exists "Public read people" on public.people;
create policy "Public read people"
  on public.people
  for select
  using (true);

drop policy if exists "Public write people" on public.people;
create policy "Public write people"
  on public.people
  for insert
  with check (true);

drop policy if exists "Public update people" on public.people;
create policy "Public update people"
  on public.people
  for update
  using (true)
  with check (true);

drop policy if exists "Public delete people" on public.people;
create policy "Public delete people"
  on public.people
  for delete
  using (true);

drop policy if exists "Public read recipe ingredients" on public.recipe_ingredients;
create policy "Public read recipe ingredients"
  on public.recipe_ingredients
  for select
  using (true);

drop policy if exists "Public write recipe ingredients" on public.recipe_ingredients;
create policy "Public write recipe ingredients"
  on public.recipe_ingredients
  for insert
  with check (true);

drop policy if exists "Public delete recipe ingredients" on public.recipe_ingredients;
create policy "Public delete recipe ingredients"
  on public.recipe_ingredients
  for delete
  using (true);

-- If you added identity to an existing table with data, run:
-- \i app/database/supabase_fix_identity.sql
