-- Phase 1: Enriched Nutrition Data Model
-- Adds food_type/barcode to ingredients, plus new tables for micronutrients and portions.
-- Run in Supabase SQL Editor → New query → paste → Run as role postgres on Primary database.

-- ---------------------------------------------------------------------------
-- 1. New columns on ingredients
-- ---------------------------------------------------------------------------

alter table public.ingredients
  add column if not exists food_type text default 'generic'
    check (food_type in ('generic', 'branded', 'custom'));

alter table public.ingredients
  add column if not exists barcode text;

alter table public.ingredients
  add column if not exists nutrition_fetched_at timestamptz;

-- Index barcodes for fast lookup (sparse — most generics won't have one)
create index if not exists idx_ingredients_barcode
  on public.ingredients (barcode) where barcode is not null;

-- ---------------------------------------------------------------------------
-- 2. Micronutrient storage (key-value per ingredient, keyed by USDA nutrient ID)
-- ---------------------------------------------------------------------------

create table if not exists public.ingredient_nutrients (
  ingredient_id bigint not null references public.ingredients(id) on delete cascade,
  nutrient_id   integer not null,
  nutrient_name text not null,
  value         real not null,
  unit          text not null,
  primary key (ingredient_id, nutrient_id)
);

alter table public.ingredient_nutrients enable row level security;

drop policy if exists "Public read ingredient_nutrients" on public.ingredient_nutrients;
create policy "Public read ingredient_nutrients"
  on public.ingredient_nutrients for select using (true);

drop policy if exists "Public write ingredient_nutrients" on public.ingredient_nutrients;
create policy "Public write ingredient_nutrients"
  on public.ingredient_nutrients for insert with check (true);

drop policy if exists "Public update ingredient_nutrients" on public.ingredient_nutrients;
create policy "Public update ingredient_nutrients"
  on public.ingredient_nutrients for update using (true) with check (true);

drop policy if exists "Public delete ingredient_nutrients" on public.ingredient_nutrients;
create policy "Public delete ingredient_nutrients"
  on public.ingredient_nutrients for delete using (true);

-- ---------------------------------------------------------------------------
-- 3. Portion sizes (multiple named portions per ingredient)
-- ---------------------------------------------------------------------------

create table if not exists public.ingredient_portions (
  id            bigint generated by default as identity primary key,
  ingredient_id bigint not null references public.ingredients(id) on delete cascade,
  gram_weight   real not null check (gram_weight > 0),
  description   text not null,
  source        text,
  is_default    boolean not null default false,
  created_at    timestamptz default now()
);

create index if not exists idx_ingredient_portions_ingredient
  on public.ingredient_portions (ingredient_id);

alter table public.ingredient_portions enable row level security;

drop policy if exists "Public read ingredient_portions" on public.ingredient_portions;
create policy "Public read ingredient_portions"
  on public.ingredient_portions for select using (true);

drop policy if exists "Public write ingredient_portions" on public.ingredient_portions;
create policy "Public write ingredient_portions"
  on public.ingredient_portions for insert with check (true);

drop policy if exists "Public update ingredient_portions" on public.ingredient_portions;
create policy "Public update ingredient_portions"
  on public.ingredient_portions for update using (true) with check (true);

drop policy if exists "Public delete ingredient_portions" on public.ingredient_portions;
create policy "Public delete ingredient_portions"
  on public.ingredient_portions for delete using (true);

-- ---------------------------------------------------------------------------
-- 4. Backfill food_type for existing branded ingredients
-- ---------------------------------------------------------------------------
-- Any ingredient that already has a brand_or_manufacturer set is likely branded.
update public.ingredients
  set food_type = 'branded'
  where brand_or_manufacturer is not null
    and brand_or_manufacturer <> ''
    and food_type = 'generic';
