-- Meal plan auto-suggestions (LLM-populated rolling 7-day calendar).
--
-- Adds:
--   * meal_plan_entries.is_suggestion        -- distinguishes LLM suggestions from user-placed meals
--   * meal_plan_entries.suggestion_pool      -- cached alternatives for the "cycle suggestion" button
--   * meal_plan_slot_dismissals              -- user trashed a suggestion; don't auto-refill this slot
--
-- Safe to re-run (idempotent). Paste the whole file into the Supabase SQL editor
-- (New query -> Run as role postgres on Primary) OR apply via your migration tool.

alter table public.meal_plan_entries
  add column if not exists is_suggestion boolean not null default false;

alter table public.meal_plan_entries
  add column if not exists suggestion_pool jsonb;

create index if not exists meal_plan_entries_suggestion_idx
  on public.meal_plan_entries (meal_plan_id, is_suggestion);

-- Hard guarantee: at most one AI suggestion per (plan, date, slot, sort_order).
-- Prevents concurrent auto-fill runs from creating duplicate cards. Real meals
-- (is_suggestion=false) are unaffected because the index is partial.
create unique index if not exists meal_plan_entries_suggestion_unique
  on public.meal_plan_entries (meal_plan_id, plan_date, meal_slot, sort_order)
  where is_suggestion = true;

create table if not exists public.meal_plan_slot_dismissals (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users (id) on delete cascade,
  plan_date date not null,
  meal_slot text not null check (
    meal_slot in ('breakfast', 'lunch', 'dinner', 'snack', 'other')
  ),
  -- sort_order lets us disambiguate snack_am (100) from snack_pm (300) since the
  -- DB meal_slot column collapses both into 'snack'. Any non-null integer is fine.
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  unique (owner_id, plan_date, meal_slot, sort_order)
);

create index if not exists meal_plan_slot_dismissals_owner_date_idx
  on public.meal_plan_slot_dismissals (owner_id, plan_date);

-- Auto-populate owner_id on insert using the same helper the other tables use.
drop trigger if exists kitchenos_meal_plan_slot_dismissals_owner
  on public.meal_plan_slot_dismissals;
create trigger kitchenos_meal_plan_slot_dismissals_owner
  before insert on public.meal_plan_slot_dismissals
  for each row
  execute function public.kitchenos_set_owner_id();

alter table public.meal_plan_slot_dismissals enable row level security;

drop policy if exists "mpsd_select" on public.meal_plan_slot_dismissals;
create policy "mpsd_select" on public.meal_plan_slot_dismissals
  for select to authenticated
  using (owner_id = auth.uid ());

drop policy if exists "mpsd_insert" on public.meal_plan_slot_dismissals;
create policy "mpsd_insert" on public.meal_plan_slot_dismissals
  for insert to authenticated
  with check (owner_id = auth.uid () or owner_id is null);

drop policy if exists "mpsd_delete" on public.meal_plan_slot_dismissals;
create policy "mpsd_delete" on public.meal_plan_slot_dismissals
  for delete to authenticated
  using (owner_id = auth.uid ());
