-- Receipt import log
--
-- Persists every receipt the user applies via the "Log a receipt" flow so
-- they can browse past imports on a dedicated /receipt-log page. We capture
-- the full raw paste plus a row per parsed line — including lines that were
-- excluded as non-food / non-inventory — so nothing the AI saw is lost.
--
-- Safe to re-run (idempotent). Paste the whole file into the Supabase SQL
-- editor: New query -> Run as role postgres on Primary.

create table if not exists public.receipt_imports (
  id bigint generated by default as identity primary key,
  owner_id uuid references auth.users (id) on delete cascade,
  raw_text text,
  item_count integer not null default 0,
  applied_count integer not null default 0,
  excluded_count integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists receipt_imports_owner_created_idx
  on public.receipt_imports (owner_id, created_at desc);

drop trigger if exists kitchenos_receipt_imports_owner
  on public.receipt_imports;
create trigger kitchenos_receipt_imports_owner
  before insert on public.receipt_imports
  for each row
  execute function public.kitchenos_set_owner_id();

alter table public.receipt_imports enable row level security;

drop policy if exists "receipt_imports_select_own" on public.receipt_imports;
create policy "receipt_imports_select_own" on public.receipt_imports
  for select to authenticated
  using (owner_id = auth.uid ());

drop policy if exists "receipt_imports_insert_own" on public.receipt_imports;
create policy "receipt_imports_insert_own" on public.receipt_imports
  for insert to authenticated
  with check (owner_id = auth.uid () or owner_id is null);

drop policy if exists "receipt_imports_update_own" on public.receipt_imports;
create policy "receipt_imports_update_own" on public.receipt_imports
  for update to authenticated
  using (owner_id = auth.uid ())
  with check (owner_id = auth.uid ());

drop policy if exists "receipt_imports_delete_own" on public.receipt_imports;
create policy "receipt_imports_delete_own" on public.receipt_imports
  for delete to authenticated
  using (owner_id = auth.uid ());


create table if not exists public.receipt_import_items (
  id bigint generated by default as identity primary key,
  import_id bigint not null references public.receipt_imports (id) on delete cascade,
  owner_id uuid references auth.users (id) on delete cascade,
  raw_line text not null,
  -- One of: 'applied' (assigned to existing ingredient), 'created' (new
  -- ingredient was created), 'ignored' (user marked ignore in review),
  -- 'excluded' (auto/manually excluded as non-inventory).
  status text not null,
  excluded_reason text,
  ingredient_id bigint references public.ingredients (id) on delete set null,
  ingredient_name text,
  product_name text,
  product_brand text,
  quantity_delta numeric,
  unit text,
  unit_size_amount numeric,
  unit_size_unit text,
  price numeric,
  price_basis text,
  price_basis_amount numeric,
  price_basis_unit text,
  purchase_quantity numeric,
  purchase_unit text,
  confidence text,
  review_flags jsonb,
  created_at timestamptz not null default now()
);

create index if not exists receipt_import_items_import_idx
  on public.receipt_import_items (import_id);

create index if not exists receipt_import_items_owner_created_idx
  on public.receipt_import_items (owner_id, created_at desc);

drop trigger if exists kitchenos_receipt_import_items_owner
  on public.receipt_import_items;
create trigger kitchenos_receipt_import_items_owner
  before insert on public.receipt_import_items
  for each row
  execute function public.kitchenos_set_owner_id();

alter table public.receipt_import_items enable row level security;

drop policy if exists "receipt_import_items_select_own" on public.receipt_import_items;
create policy "receipt_import_items_select_own" on public.receipt_import_items
  for select to authenticated
  using (owner_id = auth.uid ());

drop policy if exists "receipt_import_items_insert_own" on public.receipt_import_items;
create policy "receipt_import_items_insert_own" on public.receipt_import_items
  for insert to authenticated
  with check (owner_id = auth.uid () or owner_id is null);

drop policy if exists "receipt_import_items_update_own" on public.receipt_import_items;
create policy "receipt_import_items_update_own" on public.receipt_import_items
  for update to authenticated
  using (owner_id = auth.uid ())
  with check (owner_id = auth.uid ());

drop policy if exists "receipt_import_items_delete_own" on public.receipt_import_items;
create policy "receipt_import_items_delete_own" on public.receipt_import_items
  for delete to authenticated
  using (owner_id = auth.uid ());
