#!/usr/bin/env python3
"""
Write supabase-config.local.js (gitignored) for the Recipes UI.

  Option 1 — environment variables (paste from Supabase → Project Settings → API):
    export SUPABASE_URL="https://YOUR_REF.supabase.co"
    export SUPABASE_ANON_KEY="eyJ..."
    python3 write_supabase_local.py

  Option 2 — Supabase CLI (one browser login, then this script):
    supabase login
    python3 write_supabase_local.py

  Project ref defaults to supabase/config.toml project_id, or set SUPABASE_PROJECT_REF.
"""
from __future__ import annotations

import json
import os
import re
import subprocess
import sys
import time
from pathlib import Path

HERE = Path(__file__).resolve().parent
# app/recipes-ui -> repo root is parents[1] (kitchenOS)
REPO = HERE.parents[1]
CONFIG_TOML = REPO / "supabase" / "config.toml"
OUT = HERE / "supabase-config.local.js"


def read_project_ref_from_toml() -> str | None:
    if not CONFIG_TOML.is_file():
        return None
    text = CONFIG_TOML.read_text(encoding="utf-8")
    m = re.search(r'^\s*project_id\s*=\s*"([^"]+)"', text, re.MULTILINE)
    if not m or not m.group(1).strip():
        return None
    return m.group(1).strip()


def write_file(url: str, anon_key: str) -> None:
    body = f"""// Generated by write_supabase_local.py — do not commit (gitignored).
window.SUPABASE_CONFIG = {{
  url: {json.dumps(url)},
  anonKey: {json.dumps(anon_key)},
  bucket: "recipe-images",
}};
"""
    OUT.write_text(body, encoding="utf-8")
    print(f"Wrote {OUT}")


def pick_anon_from_api_keys_payload(data: object) -> str | None:
    if not isinstance(data, list):
        return None
    anon = None
    legacy = None
    for item in data:
        if not isinstance(item, dict):
            continue
        name = str(item.get("name") or item.get("id") or "").lower()
        key = item.get("api_key") or item.get("key") or ""
        if not key or not str(key).startswith("eyJ"):
            continue
        if "service" in name or "service_role" in name:
            continue
        if name == "anon" or "anon" in name:
            return str(key)
        if "legacy" in name or name == "default":
            legacy = str(key)
        if anon is None:
            anon = str(key)
    return anon or legacy


def fetch_keys_via_cli(project_ref: str) -> tuple[str, str] | None:
    """Call Supabase CLI; retry a few times on 401 right after `supabase login`."""
    last_err = ""
    for attempt in range(4):
        try:
            proc = subprocess.run(
                [
                    "supabase",
                    "projects",
                    "api-keys",
                    "--project-ref",
                    project_ref,
                    "-o",
                    "json",
                ],
                capture_output=True,
                text=True,
                timeout=90,
            )
        except FileNotFoundError:
            print(
                "supabase CLI not found. Install: https://supabase.com/docs/guides/cli",
                file=sys.stderr,
            )
            return None

        raw = proc.stdout.strip()
        err = (proc.stderr or proc.stdout or "").strip()
        last_err = err

        if proc.returncode == 0 and raw:
            try:
                data = json.loads(raw)
            except json.JSONDecodeError:
                print("Could not parse CLI JSON output.", file=sys.stderr)
                return None
            anon = pick_anon_from_api_keys_payload(data)
            if not anon:
                print("Could not find anon key in CLI output.", file=sys.stderr)
                return None
            url = f"https://{project_ref}.supabase.co"
            return url, anon

        if "Access token" in err or "not provided" in err:
            print(
                "Supabase CLI is not logged in. Run:\n  supabase login\nThen run this script again.",
                file=sys.stderr,
            )
            return None

        transient_401 = proc.returncode != 0 and (
            "401" in err or "Unauthorized" in err
        )
        if transient_401 and attempt < 3:
            wait = 2 + attempt * 2
            print(
                f"Supabase API returned 401 (common right after login). Retrying in {wait}s…",
                file=sys.stderr,
            )
            time.sleep(wait)
            continue

        print(err or f"supabase projects api-keys failed (exit {proc.returncode})", file=sys.stderr)
        return None

    if last_err:
        print(last_err, file=sys.stderr)
    return None


def main() -> int:
    url = os.environ.get("SUPABASE_URL", "").strip()
    key = os.environ.get("SUPABASE_ANON_KEY", "").strip()
    if url and key:
        write_file(url, key)
        return 0

    ref = os.environ.get("SUPABASE_PROJECT_REF", "").strip() or read_project_ref_from_toml() or ""
    if not ref:
        print(
            "Set SUPABASE_PROJECT_REF or add project_id to supabase/config.toml.",
            file=sys.stderr,
        )
        return 1

    got = fetch_keys_via_cli(ref)
    if not got:
        print(file=sys.stderr)
        print("Or set credentials manually:", file=sys.stderr)
        print(f'  export SUPABASE_URL="https://{ref}.supabase.co"', file=sys.stderr)
        print('  export SUPABASE_ANON_KEY="<anon key from Project Settings → API>"', file=sys.stderr)
        print("  python3 write_supabase_local.py", file=sys.stderr)
        return 1

    write_file(got[0], got[1])
    return 0


if __name__ == "__main__":
    sys.exit(main())
