/**
 * Curated seed data for the ingredient backbone catalogue.
 *
 * These entries are the **source of truth** for deterministic autofill.
 * When a new or existing ingredient name matches one of these (by canonical
 * name, normalised alias, or `ingredient_aliases` row), every field present
 * on the entry is applied to the ingredient row before any LLM is consulted.
 *
 * Guidelines for adding entries:
 * 1. Use dot-notation `backbone_id` slugs: `produce.vegetables.alliums.onion.yellow`.
 * 2. Store `canonical_name` in AP Title Case — the app rule.
 * 3. Aliases are written verbatim; the seed action normalises them with
 *    `normalizeForMatch()` before writing to the DB.
 * 4. Only include fields you are confident about. Missing fields are a
 *    legitimate signal for the LLM pass to fill later.
 * 5. Densities and unit weights are conservative, kitchen-useful approximations,
 *    not analytical chemistry. Source: USDA FoodPortions + common references.
 */

import type { BackboneCatalogueEntry } from "./ingredient-backbone-catalogue-types";

export const INGREDIENT_BACKBONE_CATALOGUE_SEED: BackboneCatalogueEntry[] = [
  // -----------------------------------------------------------------------
  // Produce — Alliums
  // -----------------------------------------------------------------------
  {
    backbone_id: "produce.vegetables.alliums.onion.yellow",
    canonical_name: "Yellow Onion",
    variant: "yellow",
    taxonomy_subcategory: "Alliums",
    grocery_category: "Produce",
    default_units: ["g", "oz", "lb", "each"],
    storage_hints: ["pantry"],
    shelf_life_counter_days: 30,
    packaged_common: false,
    canonical_unit_weight_g: 110,
    aliases: ["Yellow Onions", "Brown Onion", "Brown Onions"],
  },
  {
    backbone_id: "produce.vegetables.alliums.onion.red",
    canonical_name: "Red Onion",
    variant: "red",
    taxonomy_subcategory: "Alliums",
    grocery_category: "Produce",
    default_units: ["g", "oz", "lb", "each"],
    storage_hints: ["pantry"],
    shelf_life_counter_days: 30,
    canonical_unit_weight_g: 110,
    aliases: ["Red Onions", "Purple Onion"],
  },
  {
    backbone_id: "produce.vegetables.alliums.onion",
    canonical_name: "Onion",
    taxonomy_subcategory: "Alliums",
    grocery_category: "Produce",
    default_units: ["g", "oz", "lb", "each"],
    storage_hints: ["pantry"],
    shelf_life_counter_days: 30,
    canonical_unit_weight_g: 110,
    aliases: ["Onions", "White Onion", "White Onions", "Sweet Onion", "Sweet Onions", "Vidalia Onion"],
    notes: "Generic catch-all. Yellow / red / white variants have their own entries.",
  },
  {
    backbone_id: "produce.vegetables.alliums.shallot",
    canonical_name: "Shallot",
    taxonomy_subcategory: "Alliums",
    grocery_category: "Produce",
    default_units: ["g", "oz", "each", "clove"],
    storage_hints: ["pantry"],
    shelf_life_counter_days: 30,
    canonical_unit_weight_g: 25,
    aliases: ["Shallots", "French Shallot", "French Shallots"],
  },
  {
    backbone_id: "produce.vegetables.alliums.leek",
    canonical_name: "Leek",
    taxonomy_subcategory: "Alliums",
    grocery_category: "Produce",
    default_units: ["g", "oz", "each"],
    storage_hints: ["fridge"],
    shelf_life_fridge_days: 14,
    canonical_unit_weight_g: 150,
    aliases: ["Leeks"],
  },
  {
    backbone_id: "produce.vegetables.alliums.garlic",
    canonical_name: "Garlic",
    taxonomy_subcategory: "Alliums",
    grocery_category: "Produce",
    default_units: ["g", "clove", "head"],
    storage_hints: ["pantry"],
    shelf_life_counter_days: 90,
    canonical_unit_weight_g: 60,
    aliases: ["Garlic Head", "Head of Garlic", "Garlic Bulb"],
  },
  {
    backbone_id: "produce.vegetables.alliums.scallion",
    canonical_name: "Scallion",
    taxonomy_subcategory: "Alliums",
    grocery_category: "Produce",
    default_units: ["g", "bunch", "each"],
    storage_hints: ["fridge"],
    shelf_life_fridge_days: 10,
    aliases: ["Scallions", "Green Onion", "Green Onions", "Spring Onion", "Spring Onions"],
  },

  // -----------------------------------------------------------------------
  // Produce — Nightshades
  // -----------------------------------------------------------------------
  {
    backbone_id: "produce.vegetables.nightshades.tomato.roma",
    canonical_name: "Roma Tomato",
    variant: "roma",
    taxonomy_subcategory: "Nightshades",
    grocery_category: "Produce",
    default_units: ["g", "oz", "lb", "each"],
    storage_hints: ["counter", "fridge"],
    shelf_life_counter_days: 5,
    shelf_life_fridge_days: 7,
    canonical_unit_weight_g: 60,
    aliases: ["Roma Tomatoes", "Plum Tomato", "Plum Tomatoes"],
  },
  {
    backbone_id: "produce.vegetables.nightshades.tomato.cherry",
    canonical_name: "Cherry Tomato",
    variant: "cherry",
    taxonomy_subcategory: "Nightshades",
    grocery_category: "Produce",
    default_units: ["g", "oz", "cup", "pint"],
    storage_hints: ["counter", "fridge"],
    shelf_life_counter_days: 5,
    shelf_life_fridge_days: 7,
    canonical_unit_weight_g: 17,
    aliases: ["Cherry Tomatoes", "Grape Tomato", "Grape Tomatoes"],
  },
  {
    backbone_id: "produce.vegetables.nightshades.eggplant",
    canonical_name: "Eggplant",
    taxonomy_subcategory: "Nightshades",
    grocery_category: "Produce",
    default_units: ["g", "oz", "lb", "each"],
    storage_hints: ["counter", "fridge"],
    shelf_life_fridge_days: 7,
    canonical_unit_weight_g: 450,
    aliases: ["Aubergine", "Aubergines"],
  },
  {
    backbone_id: "produce.vegetables.nightshades.tomato",
    canonical_name: "Tomato",
    taxonomy_subcategory: "Nightshades",
    grocery_category: "Produce",
    default_units: ["g", "oz", "lb", "each"],
    storage_hints: ["counter", "fridge"],
    shelf_life_counter_days: 5,
    shelf_life_fridge_days: 7,
    canonical_unit_weight_g: 120,
    aliases: ["Tomatoes", "Vine Tomato", "Vine Tomatoes", "Beefsteak Tomato"],
    notes: "Generic catch-all. Roma / cherry have dedicated entries.",
  },
  {
    backbone_id: "produce.vegetables.nightshades.bell-pepper.red",
    canonical_name: "Red Bell Pepper",
    variant: "red",
    taxonomy_subcategory: "Nightshades",
    grocery_category: "Produce",
    default_units: ["g", "oz", "each"],
    storage_hints: ["fridge"],
    shelf_life_fridge_days: 10,
    canonical_unit_weight_g: 160,
    aliases: ["Red Bell Peppers", "Red Capsicum", "Red Sweet Pepper"],
  },
  {
    backbone_id: "produce.vegetables.nightshades.bell-pepper.green",
    canonical_name: "Green Bell Pepper",
    variant: "green",
    taxonomy_subcategory: "Nightshades",
    grocery_category: "Produce",
    default_units: ["g", "oz", "each"],
    storage_hints: ["fridge"],
    shelf_life_fridge_days: 10,
    canonical_unit_weight_g: 150,
    aliases: ["Green Bell Peppers", "Green Capsicum", "Green Pepper"],
  },
  {
    backbone_id: "produce.vegetables.nightshades.bell-pepper.yellow",
    canonical_name: "Yellow Bell Pepper",
    variant: "yellow",
    taxonomy_subcategory: "Nightshades",
    grocery_category: "Produce",
    default_units: ["g", "oz", "each"],
    storage_hints: ["fridge"],
    shelf_life_fridge_days: 10,
    canonical_unit_weight_g: 160,
    aliases: ["Yellow Bell Peppers", "Yellow Capsicum", "Orange Bell Pepper"],
  },
  {
    backbone_id: "produce.vegetables.nightshades.cucumber",
    canonical_name: "Cucumber",
    taxonomy_subcategory: "Nightshades",
    grocery_category: "Produce",
    default_units: ["g", "oz", "each"],
    storage_hints: ["fridge"],
    shelf_life_fridge_days: 7,
    canonical_unit_weight_g: 300,
    aliases: ["Cucumbers", "English Cucumber", "Persian Cucumber"],
    notes: "Botanically not a nightshade but slotted into Nightshades for culinary use; revisit if taxonomy gains a Gourds/Cucumbers subcategory.",
  },

  // -----------------------------------------------------------------------
  // Produce — Peppers & Chilies
  // -----------------------------------------------------------------------
  {
    backbone_id: "produce.vegetables.peppers.jalapeno",
    canonical_name: "Jalapeño",
    taxonomy_subcategory: "Peppers & Chilies",
    grocery_category: "Produce",
    default_units: ["g", "oz", "each"],
    storage_hints: ["fridge"],
    shelf_life_fridge_days: 14,
    canonical_unit_weight_g: 14,
    aliases: ["Jalapeno", "Jalapenos", "Jalapeños"],
  },
  {
    backbone_id: "produce.vegetables.peppers.serrano",
    canonical_name: "Serrano Pepper",
    taxonomy_subcategory: "Peppers & Chilies",
    grocery_category: "Produce",
    default_units: ["g", "oz", "each"],
    storage_hints: ["fridge"],
    shelf_life_fridge_days: 14,
    canonical_unit_weight_g: 6,
    aliases: ["Serrano", "Serranos"],
  },

  // -----------------------------------------------------------------------
  // Produce — Leafy Greens
  // -----------------------------------------------------------------------
  {
    backbone_id: "produce.vegetables.leafy-greens.spinach.baby",
    canonical_name: "Baby Spinach",
    variant: "baby",
    taxonomy_subcategory: "Leafy Greens",
    grocery_category: "Produce",
    default_units: ["g", "oz", "cup", "bag"],
    storage_hints: ["fridge"],
    shelf_life_fridge_days: 5,
    shelf_life_freezer_days: 180,
    packaged_common: true,
    aliases: ["Baby Spinach Leaves", "Baby Spinach, Washed"],
  },
  {
    backbone_id: "produce.vegetables.leafy-greens.arugula",
    canonical_name: "Arugula",
    taxonomy_subcategory: "Leafy Greens",
    grocery_category: "Produce",
    default_units: ["g", "oz", "cup", "bunch"],
    storage_hints: ["fridge"],
    shelf_life_fridge_days: 5,
    aliases: ["Rocket", "Rucola", "Roquette"],
  },
  {
    backbone_id: "produce.vegetables.leafy-greens.kale",
    canonical_name: "Kale",
    taxonomy_subcategory: "Leafy Greens",
    grocery_category: "Produce",
    default_units: ["g", "oz", "cup", "bunch"],
    storage_hints: ["fridge"],
    shelf_life_fridge_days: 7,
    aliases: ["Curly Kale", "Lacinato Kale", "Dinosaur Kale", "Tuscan Kale"],
  },

  // -----------------------------------------------------------------------
  // Produce — Brassicas
  // -----------------------------------------------------------------------
  {
    backbone_id: "produce.vegetables.brassicas.broccoli",
    canonical_name: "Broccoli",
    taxonomy_subcategory: "Brassicas",
    grocery_category: "Produce",
    default_units: ["g", "oz", "lb", "head", "floret"],
    storage_hints: ["fridge"],
    shelf_life_fridge_days: 7,
    shelf_life_freezer_days: 180,
    canonical_unit_weight_g: 450,
    aliases: ["Broccoli Crown", "Broccoli Head"],
  },
  {
    backbone_id: "produce.vegetables.brassicas.cauliflower",
    canonical_name: "Cauliflower",
    taxonomy_subcategory: "Brassicas",
    grocery_category: "Produce",
    default_units: ["g", "oz", "lb", "head", "floret"],
    storage_hints: ["fridge"],
    shelf_life_fridge_days: 14,
    canonical_unit_weight_g: 600,
    aliases: ["Cauliflower Head"],
  },
  {
    backbone_id: "produce.vegetables.brassicas.cabbage.green",
    canonical_name: "Green Cabbage",
    variant: "green",
    taxonomy_subcategory: "Brassicas",
    grocery_category: "Produce",
    default_units: ["g", "oz", "lb", "head"],
    storage_hints: ["fridge"],
    shelf_life_fridge_days: 30,
    canonical_unit_weight_g: 900,
    aliases: ["Cabbage", "White Cabbage"],
  },
  {
    backbone_id: "produce.vegetables.brassicas.cabbage.red",
    canonical_name: "Red Cabbage",
    variant: "red",
    taxonomy_subcategory: "Brassicas",
    grocery_category: "Produce",
    default_units: ["g", "oz", "lb", "head"],
    storage_hints: ["fridge"],
    shelf_life_fridge_days: 30,
    canonical_unit_weight_g: 900,
    aliases: ["Purple Cabbage"],
  },
  {
    backbone_id: "produce.vegetables.brassicas.brussels-sprouts",
    canonical_name: "Brussels Sprouts",
    taxonomy_subcategory: "Brassicas",
    grocery_category: "Produce",
    default_units: ["g", "oz", "lb", "cup", "each"],
    storage_hints: ["fridge"],
    shelf_life_fridge_days: 14,
    canonical_unit_weight_g: 20,
    aliases: ["Brussel Sprouts", "Brussels Sprout"],
  },

  // -----------------------------------------------------------------------
  // Produce — Roots & Tubers
  // -----------------------------------------------------------------------
  {
    backbone_id: "produce.vegetables.roots.potato.russet",
    canonical_name: "Russet Potato",
    variant: "russet",
    taxonomy_subcategory: "Roots & Tubers",
    grocery_category: "Produce",
    default_units: ["g", "oz", "lb", "each"],
    storage_hints: ["pantry"],
    shelf_life_counter_days: 60,
    canonical_unit_weight_g: 170,
    aliases: ["Russet Potatoes", "Idaho Potato", "Idaho Potatoes", "Baking Potato"],
  },
  {
    backbone_id: "produce.vegetables.roots.carrot",
    canonical_name: "Carrot",
    taxonomy_subcategory: "Roots & Tubers",
    grocery_category: "Produce",
    default_units: ["g", "oz", "lb", "each"],
    storage_hints: ["fridge"],
    shelf_life_fridge_days: 30,
    canonical_unit_weight_g: 60,
    aliases: ["Carrots"],
  },
  {
    backbone_id: "produce.vegetables.roots.sweet-potato",
    canonical_name: "Sweet Potato",
    taxonomy_subcategory: "Roots & Tubers",
    grocery_category: "Produce",
    default_units: ["g", "oz", "lb", "each"],
    storage_hints: ["pantry"],
    shelf_life_counter_days: 21,
    canonical_unit_weight_g: 200,
    aliases: ["Sweet Potatoes", "Yam", "Yams"],
    notes: "Culinary North American convention: 'yam' in the US usually means sweet potato.",
  },
  {
    backbone_id: "produce.vegetables.roots.beet",
    canonical_name: "Beet",
    taxonomy_subcategory: "Roots & Tubers",
    grocery_category: "Produce",
    default_units: ["g", "oz", "lb", "each"],
    storage_hints: ["fridge"],
    shelf_life_fridge_days: 21,
    canonical_unit_weight_g: 85,
    aliases: ["Beets", "Beetroot"],
  },
  {
    backbone_id: "produce.vegetables.roots.ginger",
    canonical_name: "Ginger",
    taxonomy_subcategory: "Roots & Tubers",
    grocery_category: "Produce",
    default_units: ["g", "oz", "piece", "tbsp"],
    storage_hints: ["fridge", "pantry"],
    shelf_life_fridge_days: 30,
    aliases: ["Fresh Ginger", "Ginger Root", "Gingerroot"],
  },

  // -----------------------------------------------------------------------
  // Produce — Squash / Stalk / Fungi
  // -----------------------------------------------------------------------
  {
    backbone_id: "produce.vegetables.squash.zucchini",
    canonical_name: "Zucchini",
    taxonomy_subcategory: "Squash",
    grocery_category: "Produce",
    default_units: ["g", "oz", "lb", "each"],
    storage_hints: ["fridge"],
    shelf_life_fridge_days: 7,
    canonical_unit_weight_g: 200,
    aliases: ["Courgette", "Courgettes"],
  },
  {
    backbone_id: "produce.vegetables.squash.butternut",
    canonical_name: "Butternut Squash",
    variant: "butternut",
    taxonomy_subcategory: "Squash",
    grocery_category: "Produce",
    default_units: ["g", "oz", "lb", "each"],
    storage_hints: ["pantry"],
    shelf_life_counter_days: 60,
    canonical_unit_weight_g: 1100,
  },
  {
    backbone_id: "produce.vegetables.stalks.celery",
    canonical_name: "Celery",
    taxonomy_subcategory: "Stalk Vegetables",
    grocery_category: "Produce",
    default_units: ["g", "oz", "bunch", "stalk"],
    storage_hints: ["fridge"],
    shelf_life_fridge_days: 14,
    aliases: ["Celery Stalk", "Celery Rib", "Celery Bunch"],
  },
  {
    backbone_id: "produce.vegetables.fungi.cremini",
    canonical_name: "Cremini Mushroom",
    variant: "cremini",
    taxonomy_subcategory: "Fungi",
    grocery_category: "Produce",
    default_units: ["g", "oz", "cup", "each"],
    storage_hints: ["fridge"],
    shelf_life_fridge_days: 7,
    aliases: ["Cremini Mushrooms", "Baby Bella", "Baby Bellas", "Brown Mushroom", "Brown Mushrooms"],
  },
  {
    backbone_id: "produce.vegetables.fungi.button",
    canonical_name: "Button Mushroom",
    variant: "button",
    taxonomy_subcategory: "Fungi",
    grocery_category: "Produce",
    default_units: ["g", "oz", "cup", "each"],
    storage_hints: ["fridge"],
    shelf_life_fridge_days: 7,
    aliases: ["Mushroom", "Mushrooms", "White Mushroom", "White Mushrooms", "Button Mushrooms"],
    notes: "Generic 'mushrooms' aliases here so bare 'Mushroom' entries attach to a sensible default.",
  },
  {
    backbone_id: "produce.vegetables.leafy-greens.lettuce.romaine",
    canonical_name: "Romaine Lettuce",
    variant: "romaine",
    taxonomy_subcategory: "Leafy Greens",
    grocery_category: "Produce",
    default_units: ["g", "oz", "head", "cup"],
    storage_hints: ["fridge"],
    shelf_life_fridge_days: 7,
    canonical_unit_weight_g: 360,
    aliases: ["Romaine", "Cos Lettuce", "Lettuce", "Iceberg Lettuce", "Iceberg"],
    notes: "Includes generic 'Lettuce' and 'Iceberg' as aliases so bare entries attach here.",
  },

  // -----------------------------------------------------------------------
  // Produce — Fruit
  // -----------------------------------------------------------------------
  {
    backbone_id: "produce.fruit.citrus.lemon",
    canonical_name: "Lemon",
    taxonomy_subcategory: "Citrus",
    grocery_category: "Produce",
    default_units: ["g", "oz", "each"],
    storage_hints: ["counter", "fridge"],
    shelf_life_counter_days: 7,
    shelf_life_fridge_days: 30,
    canonical_unit_weight_g: 85,
    aliases: ["Lemons"],
  },
  {
    backbone_id: "produce.fruit.citrus.lime",
    canonical_name: "Lime",
    taxonomy_subcategory: "Citrus",
    grocery_category: "Produce",
    default_units: ["g", "oz", "each"],
    storage_hints: ["counter", "fridge"],
    shelf_life_counter_days: 7,
    shelf_life_fridge_days: 30,
    canonical_unit_weight_g: 67,
    aliases: ["Limes"],
  },
  {
    backbone_id: "produce.fruit.citrus.orange",
    canonical_name: "Orange",
    taxonomy_subcategory: "Citrus",
    grocery_category: "Produce",
    default_units: ["g", "oz", "each"],
    storage_hints: ["counter", "fridge"],
    shelf_life_counter_days: 7,
    shelf_life_fridge_days: 30,
    canonical_unit_weight_g: 130,
    aliases: ["Oranges", "Navel Orange", "Valencia Orange"],
  },
  {
    backbone_id: "produce.fruit.berries.strawberry",
    canonical_name: "Strawberry",
    taxonomy_subcategory: "Berries",
    grocery_category: "Produce",
    default_units: ["g", "oz", "cup", "pint"],
    storage_hints: ["fridge"],
    shelf_life_fridge_days: 5,
    shelf_life_freezer_days: 365,
    aliases: ["Strawberries"],
  },
  {
    backbone_id: "produce.fruit.berries.blueberry",
    canonical_name: "Blueberry",
    taxonomy_subcategory: "Berries",
    grocery_category: "Produce",
    default_units: ["g", "oz", "cup", "pint"],
    storage_hints: ["fridge"],
    shelf_life_fridge_days: 7,
    shelf_life_freezer_days: 365,
    aliases: ["Blueberries"],
  },
  {
    backbone_id: "produce.fruit.berries.raspberry",
    canonical_name: "Raspberry",
    taxonomy_subcategory: "Berries",
    grocery_category: "Produce",
    default_units: ["g", "oz", "cup", "pint"],
    storage_hints: ["fridge"],
    shelf_life_fridge_days: 3,
    shelf_life_freezer_days: 365,
    aliases: ["Raspberries"],
  },
  {
    backbone_id: "produce.fruit.berries.blackberry",
    canonical_name: "Blackberry",
    taxonomy_subcategory: "Berries",
    grocery_category: "Produce",
    default_units: ["g", "oz", "cup", "pint"],
    storage_hints: ["fridge"],
    shelf_life_fridge_days: 3,
    shelf_life_freezer_days: 365,
    aliases: ["Blackberries"],
  },
  {
    backbone_id: "produce.fruit.pome.apple",
    canonical_name: "Apple",
    taxonomy_subcategory: "Pome Fruit",
    grocery_category: "Produce",
    default_units: ["g", "oz", "each"],
    storage_hints: ["counter", "fridge"],
    shelf_life_counter_days: 7,
    shelf_life_fridge_days: 30,
    canonical_unit_weight_g: 180,
    aliases: ["Apples", "Gala Apple", "Honeycrisp", "Honeycrisp Apple", "Granny Smith", "Granny Smith Apple", "Fuji Apple"],
  },
  {
    backbone_id: "produce.fruit.tropical.banana",
    canonical_name: "Banana",
    taxonomy_subcategory: "Tropical Fruit",
    grocery_category: "Produce",
    default_units: ["g", "oz", "each"],
    storage_hints: ["counter"],
    shelf_life_counter_days: 5,
    canonical_unit_weight_g: 120,
    aliases: ["Bananas"],
  },
  {
    backbone_id: "produce.fruit.tropical.avocado",
    canonical_name: "Avocado",
    taxonomy_subcategory: "Tropical Fruit",
    grocery_category: "Produce",
    default_units: ["g", "oz", "each"],
    storage_hints: ["counter", "fridge"],
    shelf_life_counter_days: 5,
    shelf_life_fridge_days: 7,
    canonical_unit_weight_g: 170,
    aliases: ["Avocados", "Hass Avocado"],
  },
  {
    backbone_id: "produce.fruit.tropical.mango",
    canonical_name: "Mango",
    taxonomy_subcategory: "Tropical Fruit",
    grocery_category: "Produce",
    default_units: ["g", "oz", "cup", "each"],
    storage_hints: ["counter", "fridge"],
    shelf_life_counter_days: 5,
    shelf_life_fridge_days: 7,
    canonical_unit_weight_g: 340,
    aliases: ["Mangos", "Mangoes"],
  },

  // -----------------------------------------------------------------------
  // Herbs & spices
  // -----------------------------------------------------------------------
  {
    backbone_id: "herbs.fresh.basil",
    canonical_name: "Basil",
    taxonomy_subcategory: "Fresh Herbs",
    grocery_category: "Produce",
    default_units: ["g", "oz", "bunch", "cup", "leaf"],
    storage_hints: ["fridge"],
    shelf_life_fridge_days: 5,
    aliases: ["Fresh Basil", "Basil Leaves", "Sweet Basil"],
  },
  {
    backbone_id: "herbs.fresh.cilantro",
    canonical_name: "Cilantro",
    taxonomy_subcategory: "Fresh Herbs",
    grocery_category: "Produce",
    default_units: ["g", "oz", "bunch", "cup", "tbsp"],
    storage_hints: ["fridge"],
    shelf_life_fridge_days: 5,
    aliases: ["Coriander Leaves", "Fresh Coriander", "Chinese Parsley", "Coriander Leaf"],
  },
  {
    backbone_id: "herbs.fresh.parsley",
    canonical_name: "Parsley",
    taxonomy_subcategory: "Fresh Herbs",
    grocery_category: "Produce",
    default_units: ["g", "oz", "bunch", "cup", "tbsp"],
    storage_hints: ["fridge"],
    shelf_life_fridge_days: 7,
    aliases: ["Flat-Leaf Parsley", "Italian Parsley", "Fresh Parsley", "Curly Parsley"],
  },
  {
    backbone_id: "spices.black-pepper",
    canonical_name: "Black Pepper",
    taxonomy_subcategory: "Dried Spices",
    grocery_category: "Pantry",
    default_units: ["g", "tsp", "tbsp"],
    storage_hints: ["pantry"],
    packaged_common: true,
    density_g_per_ml: 0.52,
    aliases: ["Ground Black Pepper", "Cracked Black Pepper", "Peppercorn", "Peppercorns"],
  },
  {
    backbone_id: "spices.cumin",
    canonical_name: "Ground Cumin",
    taxonomy_subcategory: "Dried Spices",
    grocery_category: "Pantry",
    default_units: ["g", "tsp", "tbsp"],
    storage_hints: ["pantry"],
    packaged_common: true,
    density_g_per_ml: 0.48,
    aliases: ["Cumin", "Cumin Powder"],
  },
  {
    backbone_id: "spices.cinnamon",
    canonical_name: "Ground Cinnamon",
    taxonomy_subcategory: "Dried Spices",
    grocery_category: "Pantry",
    default_units: ["g", "tsp", "tbsp"],
    storage_hints: ["pantry"],
    packaged_common: true,
    density_g_per_ml: 0.56,
    aliases: ["Cinnamon", "Cinnamon Powder"],
  },

  // -----------------------------------------------------------------------
  // Grains / flours / pasta
  // -----------------------------------------------------------------------
  {
    backbone_id: "grains.rice.brown",
    canonical_name: "Brown Rice",
    variant: "brown",
    taxonomy_subcategory: "Whole Grains",
    grocery_category: "Pantry",
    default_units: ["g", "oz", "cup", "lb"],
    storage_hints: ["pantry"],
    packaged_common: true,
    density_g_per_ml: 0.83,
    aliases: ["Whole-Grain Rice", "Long-Grain Brown Rice"],
  },
  {
    backbone_id: "grains.quinoa",
    canonical_name: "Quinoa",
    taxonomy_subcategory: "Whole Grains",
    grocery_category: "Pantry",
    default_units: ["g", "oz", "cup", "lb"],
    storage_hints: ["pantry"],
    packaged_common: true,
    density_g_per_ml: 0.76,
    aliases: ["White Quinoa", "Tri-Color Quinoa", "Red Quinoa"],
  },
  {
    backbone_id: "grains.oats.rolled",
    canonical_name: "Rolled Oats",
    variant: "rolled",
    taxonomy_subcategory: "Whole Grains",
    grocery_category: "Breakfast & Cereal",
    default_units: ["g", "oz", "cup"],
    storage_hints: ["pantry"],
    packaged_common: true,
    density_g_per_ml: 0.41,
    aliases: ["Oats", "Old-Fashioned Oats", "Porridge Oats"],
  },
  {
    backbone_id: "flours.all-purpose",
    canonical_name: "All-Purpose Flour",
    taxonomy_subcategory: "Flours & Starches",
    grocery_category: "Pantry",
    default_units: ["g", "oz", "cup", "lb"],
    storage_hints: ["pantry"],
    packaged_common: true,
    density_g_per_ml: 0.53,
    aliases: ["Plain Flour", "AP Flour", "White Flour"],
  },
  {
    backbone_id: "flours.cornstarch",
    canonical_name: "Cornstarch",
    taxonomy_subcategory: "Flours & Starches",
    grocery_category: "Pantry",
    default_units: ["g", "tsp", "tbsp", "cup"],
    storage_hints: ["pantry"],
    packaged_common: true,
    density_g_per_ml: 0.63,
    aliases: ["Corn Starch", "Corn Flour"],
    notes: "In the UK 'corn flour' can mean cornstarch; if you're importing UK recipes this alias matters.",
  },
  {
    backbone_id: "pasta.spaghetti",
    canonical_name: "Spaghetti",
    taxonomy_subcategory: "Pasta & Noodles",
    grocery_category: "Pantry",
    default_units: ["g", "oz", "lb"],
    storage_hints: ["pantry"],
    packaged_common: true,
    aliases: ["Dry Spaghetti", "Spaghettini"],
  },
  {
    backbone_id: "pasta.penne",
    canonical_name: "Penne",
    taxonomy_subcategory: "Pasta & Noodles",
    grocery_category: "Pantry",
    default_units: ["g", "oz", "lb"],
    storage_hints: ["pantry"],
    packaged_common: true,
    aliases: ["Penne Rigate", "Penne Pasta"],
  },
  {
    backbone_id: "pasta.lasagna",
    canonical_name: "Lasagna Noodles",
    taxonomy_subcategory: "Pasta & Noodles",
    grocery_category: "Pantry",
    default_units: ["g", "oz", "lb", "sheet"],
    storage_hints: ["pantry"],
    packaged_common: true,
    aliases: ["Lasagna", "Lasagne Noodles", "Lasagne Sheets", "Lasagna Sheets"],
  },
  {
    backbone_id: "grains.rice.white",
    canonical_name: "White Rice",
    variant: "white",
    taxonomy_subcategory: "Whole Grains",
    grocery_category: "Pantry",
    default_units: ["g", "oz", "cup", "lb"],
    storage_hints: ["pantry"],
    packaged_common: true,
    density_g_per_ml: 0.85,
    aliases: ["Rice", "Long-Grain White Rice", "Jasmine Rice", "Basmati Rice"],
    notes: "Culinary default for bare 'Rice'; brown / specialty rices get their own entries.",
  },
  {
    backbone_id: "bakery.pizza-dough",
    canonical_name: "Pizza Dough",
    taxonomy_subcategory: "Flours & Starches",
    grocery_category: "Bakery & Bread",
    default_units: ["g", "oz", "ball", "lb"],
    storage_hints: ["fridge", "freezer"],
    shelf_life_fridge_days: 3,
    shelf_life_freezer_days: 60,
    packaged_common: true,
    is_composite: true,
    canonical_unit_weight_g: 450,
    aliases: ["Fresh Pizza Dough", "Pizza Dough Ball"],
  },
  {
    backbone_id: "bakery.bread.sliced",
    canonical_name: "Sliced Bread",
    variant: "sliced",
    taxonomy_subcategory: "Flours & Starches",
    grocery_category: "Bakery & Bread",
    default_units: ["g", "oz", "slice", "loaf"],
    storage_hints: ["pantry", "freezer"],
    shelf_life_counter_days: 5,
    shelf_life_freezer_days: 90,
    packaged_common: true,
    is_composite: true,
    aliases: ["Bread", "Loaf of Bread", "White Bread", "Whole Wheat Bread", "Sourdough"],
    notes: "Generic bread catch-all so bare 'Bread' entries attach to something.",
  },
  {
    backbone_id: "bakery.tortilla.flour",
    canonical_name: "Flour Tortilla",
    variant: "flour",
    taxonomy_subcategory: "Flours & Starches",
    grocery_category: "Bakery & Bread",
    default_units: ["each", "g"],
    storage_hints: ["pantry", "fridge", "freezer"],
    shelf_life_fridge_days: 14,
    shelf_life_freezer_days: 180,
    packaged_common: true,
    is_composite: true,
    canonical_unit_weight_g: 35,
    aliases: ["Tortilla", "Tortillas", "Flour Tortillas", "Burrito Tortilla"],
  },
  {
    backbone_id: "bakery.tortilla.corn",
    canonical_name: "Corn Tortilla",
    variant: "corn",
    taxonomy_subcategory: "Flours & Starches",
    grocery_category: "Bakery & Bread",
    default_units: ["each", "g"],
    storage_hints: ["fridge", "freezer"],
    shelf_life_fridge_days: 21,
    shelf_life_freezer_days: 180,
    packaged_common: true,
    is_composite: true,
    canonical_unit_weight_g: 25,
    aliases: ["Corn Tortillas", "Yellow Corn Tortilla", "White Corn Tortilla"],
  },

  // -----------------------------------------------------------------------
  // Legumes
  // -----------------------------------------------------------------------
  {
    backbone_id: "legumes.dried.chickpea",
    canonical_name: "Dried Chickpeas",
    taxonomy_subcategory: "Dried Legumes",
    grocery_category: "Pantry",
    default_units: ["g", "oz", "cup", "lb"],
    storage_hints: ["pantry"],
    packaged_common: true,
    aliases: ["Garbanzo Beans", "Dried Garbanzo Beans", "Chickpeas, Dried"],
  },
  {
    backbone_id: "legumes.canned.chickpea",
    canonical_name: "Canned Chickpeas",
    variant: "canned",
    taxonomy_subcategory: "Canned Legumes",
    grocery_category: "Pantry",
    default_units: ["can", "g", "oz", "cup"],
    storage_hints: ["pantry"],
    packaged_common: true,
    aliases: ["Canned Garbanzo Beans", "Chickpeas in a Can"],
  },
  {
    backbone_id: "legumes.canned.black-bean",
    canonical_name: "Canned Black Beans",
    variant: "canned",
    taxonomy_subcategory: "Canned Legumes",
    grocery_category: "Pantry",
    default_units: ["can", "g", "oz", "cup"],
    storage_hints: ["pantry"],
    packaged_common: true,
    aliases: ["Black Beans, Canned"],
  },

  // -----------------------------------------------------------------------
  // Nuts / seeds / butters
  // -----------------------------------------------------------------------
  {
    backbone_id: "nuts.almond",
    canonical_name: "Almonds",
    taxonomy_subcategory: "Nuts",
    grocery_category: "Pantry",
    default_units: ["g", "oz", "cup"],
    storage_hints: ["pantry", "freezer"],
    shelf_life_fridge_days: 180,
    shelf_life_freezer_days: 365,
    packaged_common: true,
    aliases: ["Raw Almonds", "Whole Almonds", "Almond"],
  },
  {
    backbone_id: "seeds.chia",
    canonical_name: "Chia Seeds",
    taxonomy_subcategory: "Seeds",
    grocery_category: "Pantry",
    default_units: ["g", "oz", "tbsp", "cup"],
    storage_hints: ["pantry"],
    shelf_life_fridge_days: 365,
    packaged_common: true,
    aliases: ["Chia", "Chia Seed"],
  },
  {
    backbone_id: "butters.peanut",
    canonical_name: "Peanut Butter",
    taxonomy_subcategory: "Nut & Seed Butters",
    grocery_category: "Pantry",
    default_units: ["g", "oz", "tbsp", "cup"],
    storage_hints: ["pantry", "fridge"],
    shelf_life_fridge_days: 90,
    packaged_common: true,
    is_composite: true,
    density_g_per_ml: 1.08,
    aliases: ["Smooth Peanut Butter", "Crunchy Peanut Butter", "Natural Peanut Butter"],
  },
  {
    backbone_id: "butters.tahini",
    canonical_name: "Tahini",
    taxonomy_subcategory: "Nut & Seed Butters",
    grocery_category: "Pantry",
    default_units: ["g", "oz", "tbsp", "cup"],
    storage_hints: ["pantry", "fridge"],
    shelf_life_fridge_days: 180,
    packaged_common: true,
    is_composite: true,
    density_g_per_ml: 1.08,
    aliases: ["Sesame Paste", "Sesame Butter"],
  },

  // -----------------------------------------------------------------------
  // Fats / acids / sweeteners / baking
  // -----------------------------------------------------------------------
  {
    backbone_id: "oils.olive.evoo",
    canonical_name: "Extra Virgin Olive Oil",
    variant: "extra virgin",
    taxonomy_subcategory: "Oils & Fats",
    grocery_category: "Pantry",
    default_units: ["ml", "tsp", "tbsp", "cup"],
    storage_hints: ["pantry"],
    packaged_common: true,
    density_g_per_ml: 0.91,
    aliases: ["EVOO", "Olive Oil", "Cold-Pressed Olive Oil"],
  },
  {
    backbone_id: "oils.coconut",
    canonical_name: "Coconut Oil",
    taxonomy_subcategory: "Oils & Fats",
    grocery_category: "Pantry",
    default_units: ["ml", "g", "tsp", "tbsp", "cup"],
    storage_hints: ["pantry"],
    packaged_common: true,
    density_g_per_ml: 0.92,
    aliases: ["Virgin Coconut Oil", "Refined Coconut Oil"],
  },
  {
    backbone_id: "dairy.fats.butter",
    canonical_name: "Butter",
    taxonomy_subcategory: "Oils & Fats",
    grocery_category: "Dairy & Eggs",
    default_units: ["g", "oz", "tbsp", "cup", "stick"],
    storage_hints: ["fridge", "freezer"],
    shelf_life_fridge_days: 60,
    shelf_life_freezer_days: 180,
    packaged_common: true,
    density_g_per_ml: 0.91,
    canonical_unit_weight_g: 113,
    aliases: ["Unsalted Butter", "Salted Butter", "Stick of Butter"],
    notes: "US stick = 4 oz / ~113 g. UK block = 250 g.",
  },
  {
    backbone_id: "vinegars.apple-cider",
    canonical_name: "Apple Cider Vinegar",
    taxonomy_subcategory: "Vinegars",
    grocery_category: "Pantry",
    default_units: ["ml", "tsp", "tbsp", "cup"],
    storage_hints: ["pantry"],
    packaged_common: true,
    density_g_per_ml: 1.01,
    aliases: ["ACV", "Cider Vinegar"],
  },
  {
    backbone_id: "vinegars.balsamic",
    canonical_name: "Balsamic Vinegar",
    taxonomy_subcategory: "Vinegars",
    grocery_category: "Pantry",
    default_units: ["ml", "tsp", "tbsp", "cup"],
    storage_hints: ["pantry"],
    packaged_common: true,
    density_g_per_ml: 1.08,
    aliases: ["Balsamic", "Aged Balsamic"],
  },
  {
    backbone_id: "sweeteners.maple-syrup",
    canonical_name: "Maple Syrup",
    taxonomy_subcategory: "Sweeteners",
    grocery_category: "Pantry",
    default_units: ["ml", "tsp", "tbsp", "cup"],
    storage_hints: ["pantry", "fridge"],
    shelf_life_fridge_days: 365,
    packaged_common: true,
    density_g_per_ml: 1.33,
    aliases: ["Pure Maple Syrup", "Grade A Maple Syrup"],
  },
  {
    backbone_id: "sweeteners.honey",
    canonical_name: "Honey",
    taxonomy_subcategory: "Sweeteners",
    grocery_category: "Pantry",
    default_units: ["g", "oz", "tsp", "tbsp", "cup"],
    storage_hints: ["pantry"],
    packaged_common: true,
    density_g_per_ml: 1.42,
    aliases: ["Raw Honey", "Clover Honey", "Wildflower Honey"],
  },
  {
    backbone_id: "sweeteners.sugar.granulated",
    canonical_name: "Granulated Sugar",
    variant: "granulated",
    taxonomy_subcategory: "Sweeteners",
    grocery_category: "Pantry",
    default_units: ["g", "oz", "tsp", "tbsp", "cup"],
    storage_hints: ["pantry"],
    packaged_common: true,
    density_g_per_ml: 0.85,
    aliases: ["Sugar", "White Sugar", "Cane Sugar", "Caster Sugar"],
  },
  {
    backbone_id: "baking.baking-powder",
    canonical_name: "Baking Powder",
    taxonomy_subcategory: "Baking Essentials",
    grocery_category: "Pantry",
    default_units: ["g", "tsp", "tbsp"],
    storage_hints: ["pantry"],
    packaged_common: true,
    density_g_per_ml: 0.96,
  },
  {
    backbone_id: "baking.baking-soda",
    canonical_name: "Baking Soda",
    taxonomy_subcategory: "Baking Essentials",
    grocery_category: "Pantry",
    default_units: ["g", "tsp", "tbsp"],
    storage_hints: ["pantry"],
    packaged_common: true,
    density_g_per_ml: 2.20,
    aliases: ["Bicarbonate of Soda", "Bicarb", "Sodium Bicarbonate"],
  },
  {
    backbone_id: "baking.vanilla-extract",
    canonical_name: "Vanilla Extract",
    taxonomy_subcategory: "Baking Essentials",
    grocery_category: "Pantry",
    default_units: ["ml", "tsp", "tbsp"],
    storage_hints: ["pantry"],
    packaged_common: true,
    density_g_per_ml: 0.88,
    aliases: ["Pure Vanilla Extract", "Vanilla"],
  },

  // -----------------------------------------------------------------------
  // Canned tomatoes / broths / condiments
  // -----------------------------------------------------------------------
  {
    backbone_id: "canned.tomato.diced",
    canonical_name: "Canned Diced Tomatoes",
    variant: "canned diced",
    taxonomy_subcategory: "Canned Tomatoes",
    grocery_category: "Pantry",
    default_units: ["can", "g", "oz", "cup"],
    storage_hints: ["pantry"],
    shelf_life_fridge_days: 5,
    packaged_common: true,
    aliases: ["Diced Tomatoes", "Diced Tomatoes in Juice", "Canned Tomatoes"],
  },
  {
    backbone_id: "canned.tomato.paste",
    canonical_name: "Tomato Paste",
    variant: "paste",
    taxonomy_subcategory: "Canned Tomatoes",
    grocery_category: "Pantry",
    default_units: ["g", "oz", "tsp", "tbsp", "can"],
    storage_hints: ["pantry", "fridge"],
    shelf_life_fridge_days: 7,
    packaged_common: true,
    is_composite: true,
    density_g_per_ml: 1.07,
    aliases: ["Double-Concentrate Tomato Paste", "Concentrated Tomato"],
  },
  {
    backbone_id: "broths.chicken",
    canonical_name: "Chicken Broth",
    taxonomy_subcategory: "Broths & Stocks",
    grocery_category: "Pantry",
    default_units: ["ml", "cup", "carton", "can"],
    storage_hints: ["pantry", "fridge"],
    shelf_life_fridge_days: 5,
    shelf_life_freezer_days: 90,
    packaged_common: true,
    is_composite: true,
    density_g_per_ml: 1.01,
    aliases: ["Chicken Stock", "Low-Sodium Chicken Broth"],
  },
  {
    backbone_id: "broths.vegetable",
    canonical_name: "Vegetable Broth",
    taxonomy_subcategory: "Broths & Stocks",
    grocery_category: "Pantry",
    default_units: ["ml", "cup", "carton", "can"],
    storage_hints: ["pantry", "fridge"],
    shelf_life_fridge_days: 5,
    shelf_life_freezer_days: 90,
    packaged_common: true,
    is_composite: true,
    density_g_per_ml: 1.01,
    aliases: ["Vegetable Stock", "Veggie Broth"],
  },
  {
    backbone_id: "condiments.soy-sauce",
    canonical_name: "Soy Sauce",
    taxonomy_subcategory: "Condiments & Sauces",
    grocery_category: "Pantry",
    default_units: ["ml", "tsp", "tbsp", "cup"],
    storage_hints: ["pantry", "fridge"],
    shelf_life_fridge_days: 365,
    packaged_common: true,
    is_composite: true,
    density_g_per_ml: 1.19,
    aliases: ["Tamari", "Shoyu", "Light Soy Sauce", "Dark Soy Sauce"],
    notes: "Tamari is technically gluten-free soy sauce; aliased here for recipe matching.",
  },
  {
    backbone_id: "condiments.mayonnaise",
    canonical_name: "Mayonnaise",
    taxonomy_subcategory: "Condiments & Sauces",
    grocery_category: "Pantry",
    default_units: ["g", "tsp", "tbsp", "cup"],
    storage_hints: ["fridge"],
    shelf_life_fridge_days: 60,
    packaged_common: true,
    is_composite: true,
    density_g_per_ml: 0.92,
    aliases: ["Mayo", "Real Mayonnaise"],
  },
  {
    backbone_id: "condiments.ketchup",
    canonical_name: "Ketchup",
    taxonomy_subcategory: "Condiments & Sauces",
    grocery_category: "Pantry",
    default_units: ["g", "tsp", "tbsp", "cup"],
    storage_hints: ["pantry", "fridge"],
    shelf_life_fridge_days: 180,
    packaged_common: true,
    is_composite: true,
    density_g_per_ml: 1.15,
    aliases: ["Tomato Ketchup", "Catsup"],
  },
  {
    backbone_id: "condiments.sriracha",
    canonical_name: "Sriracha",
    taxonomy_subcategory: "Condiments & Sauces",
    grocery_category: "Pantry",
    default_units: ["ml", "tsp", "tbsp"],
    storage_hints: ["pantry", "fridge"],
    shelf_life_fridge_days: 365,
    packaged_common: true,
    is_composite: true,
    density_g_per_ml: 1.12,
    aliases: ["Sriracha Sauce", "Hot Chili Sauce"],
  },
  {
    backbone_id: "condiments.fish-sauce",
    canonical_name: "Fish Sauce",
    taxonomy_subcategory: "Condiments & Sauces",
    grocery_category: "Pantry",
    default_units: ["ml", "tsp", "tbsp"],
    storage_hints: ["pantry"],
    shelf_life_fridge_days: 730,
    packaged_common: true,
    is_composite: true,
    density_g_per_ml: 1.22,
    aliases: ["Nam Pla", "Nuoc Mam"],
  },
  {
    backbone_id: "condiments.dijon-mustard",
    canonical_name: "Dijon Mustard",
    variant: "dijon",
    taxonomy_subcategory: "Condiments & Sauces",
    grocery_category: "Pantry",
    default_units: ["g", "tsp", "tbsp", "cup"],
    storage_hints: ["fridge"],
    shelf_life_fridge_days: 365,
    packaged_common: true,
    is_composite: true,
    density_g_per_ml: 1.07,
    aliases: ["Dijon"],
  },

  // -----------------------------------------------------------------------
  // Dairy / eggs / plant milks
  // -----------------------------------------------------------------------
  {
    backbone_id: "dairy.milk.whole",
    canonical_name: "Whole Milk",
    variant: "whole",
    taxonomy_subcategory: "Dairy",
    grocery_category: "Dairy & Eggs",
    default_units: ["ml", "cup", "carton"],
    storage_hints: ["fridge"],
    shelf_life_fridge_days: 7,
    packaged_common: true,
    density_g_per_ml: 1.03,
    aliases: ["Full-Fat Milk", "Vitamin D Milk"],
  },
  {
    backbone_id: "dairy.yogurt.plain",
    canonical_name: "Plain Yogurt",
    variant: "plain",
    taxonomy_subcategory: "Dairy",
    grocery_category: "Dairy & Eggs",
    default_units: ["g", "oz", "cup"],
    storage_hints: ["fridge"],
    shelf_life_fridge_days: 14,
    packaged_common: true,
    density_g_per_ml: 1.03,
    aliases: ["Plain Whole-Milk Yogurt", "Greek Yogurt, Plain", "Plain Greek Yogurt"],
  },
  {
    backbone_id: "dairy.cheese.parmesan",
    canonical_name: "Parmesan",
    taxonomy_subcategory: "Cheese",
    grocery_category: "Dairy & Eggs",
    default_units: ["g", "oz", "cup"],
    storage_hints: ["fridge"],
    shelf_life_fridge_days: 60,
    packaged_common: true,
    aliases: ["Parmesan Cheese", "Parmigiano-Reggiano", "Parmigiano Reggiano"],
  },
  {
    backbone_id: "dairy.cheese.feta",
    canonical_name: "Feta",
    taxonomy_subcategory: "Cheese",
    grocery_category: "Dairy & Eggs",
    default_units: ["g", "oz", "cup"],
    storage_hints: ["fridge"],
    shelf_life_fridge_days: 30,
    packaged_common: true,
    aliases: ["Feta Cheese", "Greek Feta"],
  },
  {
    backbone_id: "dairy.cheese.cheddar",
    canonical_name: "Cheddar",
    taxonomy_subcategory: "Cheese",
    grocery_category: "Dairy & Eggs",
    default_units: ["g", "oz", "cup", "slice"],
    storage_hints: ["fridge"],
    shelf_life_fridge_days: 60,
    packaged_common: true,
    aliases: ["Cheddar Cheese", "Sharp Cheddar", "Mild Cheddar", "Aged Cheddar"],
  },
  {
    backbone_id: "dairy.cheese.mozzarella",
    canonical_name: "Mozzarella",
    taxonomy_subcategory: "Cheese",
    grocery_category: "Dairy & Eggs",
    default_units: ["g", "oz", "cup", "ball"],
    storage_hints: ["fridge"],
    shelf_life_fridge_days: 14,
    packaged_common: true,
    aliases: ["Mozzarella Cheese", "Fresh Mozzarella", "Shredded Mozzarella", "Low-Moisture Mozzarella"],
  },
  {
    backbone_id: "dairy.cheese.goat",
    canonical_name: "Goat Cheese",
    taxonomy_subcategory: "Cheese",
    grocery_category: "Dairy & Eggs",
    default_units: ["g", "oz", "cup"],
    storage_hints: ["fridge"],
    shelf_life_fridge_days: 21,
    packaged_common: true,
    aliases: ["Chèvre", "Chevre", "Goat's Cheese", "Soft Goat Cheese"],
  },
  {
    backbone_id: "dairy.cheese.cream",
    canonical_name: "Cream Cheese",
    taxonomy_subcategory: "Cheese",
    grocery_category: "Dairy & Eggs",
    default_units: ["g", "oz", "tbsp", "cup", "block"],
    storage_hints: ["fridge"],
    shelf_life_fridge_days: 21,
    packaged_common: true,
    is_composite: true,
    density_g_per_ml: 1.01,
    canonical_unit_weight_g: 226,
    aliases: ["Cream Cheese Block", "Full-Fat Cream Cheese"],
  },
  {
    backbone_id: "dairy.sour-cream",
    canonical_name: "Sour Cream",
    taxonomy_subcategory: "Dairy",
    grocery_category: "Dairy & Eggs",
    default_units: ["g", "oz", "cup", "tbsp"],
    storage_hints: ["fridge"],
    shelf_life_fridge_days: 21,
    packaged_common: true,
    density_g_per_ml: 0.96,
    aliases: ["Light Sour Cream", "Full-Fat Sour Cream"],
  },
  {
    backbone_id: "dairy.cream.heavy",
    canonical_name: "Heavy Cream",
    variant: "heavy",
    taxonomy_subcategory: "Dairy",
    grocery_category: "Dairy & Eggs",
    default_units: ["ml", "cup", "tbsp"],
    storage_hints: ["fridge"],
    shelf_life_fridge_days: 14,
    packaged_common: true,
    density_g_per_ml: 0.99,
    aliases: ["Heavy Whipping Cream", "Double Cream", "Whipping Cream"],
  },
  {
    backbone_id: "dairy.eggs.large",
    canonical_name: "Large Egg",
    variant: "large",
    taxonomy_subcategory: "Eggs",
    grocery_category: "Dairy & Eggs",
    default_units: ["each", "dozen"],
    storage_hints: ["fridge"],
    shelf_life_fridge_days: 35,
    packaged_common: true,
    canonical_unit_weight_g: 57,
    aliases: ["Egg", "Eggs", "Large Eggs", "Chicken Egg"],
  },
  {
    backbone_id: "plant-milks.almond",
    canonical_name: "Almond Milk",
    taxonomy_subcategory: "Plant Milks",
    grocery_category: "Beverages",
    default_units: ["ml", "cup", "carton"],
    storage_hints: ["pantry", "fridge"],
    shelf_life_fridge_days: 7,
    packaged_common: true,
    is_composite: true,
    density_g_per_ml: 1.01,
    aliases: ["Unsweetened Almond Milk", "Sweetened Almond Milk"],
  },
  {
    backbone_id: "plant-milks.oat",
    canonical_name: "Oat Milk",
    taxonomy_subcategory: "Plant Milks",
    grocery_category: "Beverages",
    default_units: ["ml", "cup", "carton"],
    storage_hints: ["pantry", "fridge"],
    shelf_life_fridge_days: 7,
    packaged_common: true,
    is_composite: true,
    density_g_per_ml: 1.02,
    aliases: ["Barista Oat Milk"],
  },
  {
    backbone_id: "soy-proteins.tofu.firm",
    canonical_name: "Firm Tofu",
    variant: "firm",
    taxonomy_subcategory: "Soy Proteins",
    grocery_category: "Produce",
    default_units: ["g", "oz", "block"],
    storage_hints: ["fridge"],
    shelf_life_fridge_days: 7,
    shelf_life_freezer_days: 90,
    packaged_common: true,
    is_composite: true,
    canonical_unit_weight_g: 397,
    aliases: ["Extra-Firm Tofu", "Tofu", "Firm Tofu Block"],
  },

  // -----------------------------------------------------------------------
  // Proteins — meat, poultry, seafood
  // -----------------------------------------------------------------------
  {
    backbone_id: "meat.beef.ground",
    canonical_name: "Ground Beef",
    taxonomy_subcategory: "Meat",
    grocery_category: "Meat & Seafood",
    default_units: ["g", "oz", "lb"],
    storage_hints: ["fridge", "freezer"],
    shelf_life_fridge_days: 2,
    shelf_life_freezer_days: 120,
    packaged_common: true,
    aliases: ["Minced Beef", "Beef Mince", "80/20 Ground Beef", "85/15 Ground Beef"],
  },
  {
    backbone_id: "meat.pork.bacon",
    canonical_name: "Bacon",
    taxonomy_subcategory: "Meat",
    grocery_category: "Meat & Seafood",
    default_units: ["g", "oz", "lb", "slice", "strip"],
    storage_hints: ["fridge", "freezer"],
    shelf_life_fridge_days: 7,
    shelf_life_freezer_days: 30,
    packaged_common: true,
    aliases: ["Streaky Bacon", "Smoked Bacon"],
  },
  {
    backbone_id: "poultry.chicken.breast.boneless-skinless",
    canonical_name: "Boneless Skinless Chicken Breast",
    variant: "boneless skinless",
    taxonomy_subcategory: "Poultry",
    grocery_category: "Meat & Seafood",
    default_units: ["g", "oz", "lb", "each"],
    storage_hints: ["fridge", "freezer"],
    shelf_life_fridge_days: 2,
    shelf_life_freezer_days: 270,
    packaged_common: true,
    canonical_unit_weight_g: 200,
    aliases: ["Chicken Breast", "Chicken Breasts", "Skinless Chicken Breast", "Chicken Breast Fillet"],
  },
  {
    backbone_id: "poultry.chicken.ground",
    canonical_name: "Ground Chicken",
    taxonomy_subcategory: "Poultry",
    grocery_category: "Meat & Seafood",
    default_units: ["g", "oz", "lb"],
    storage_hints: ["fridge", "freezer"],
    shelf_life_fridge_days: 2,
    shelf_life_freezer_days: 120,
    packaged_common: true,
    aliases: ["Minced Chicken"],
  },
  {
    backbone_id: "poultry.turkey.ground",
    canonical_name: "Ground Turkey",
    taxonomy_subcategory: "Poultry",
    grocery_category: "Meat & Seafood",
    default_units: ["g", "oz", "lb"],
    storage_hints: ["fridge", "freezer"],
    shelf_life_fridge_days: 2,
    shelf_life_freezer_days: 120,
    packaged_common: true,
    aliases: ["Minced Turkey"],
  },
  {
    backbone_id: "poultry.chicken.thigh.boneless-skinless",
    canonical_name: "Boneless Skinless Chicken Thigh",
    variant: "boneless skinless",
    taxonomy_subcategory: "Poultry",
    grocery_category: "Meat & Seafood",
    default_units: ["g", "oz", "lb", "each"],
    storage_hints: ["fridge", "freezer"],
    shelf_life_fridge_days: 2,
    shelf_life_freezer_days: 270,
    packaged_common: true,
    canonical_unit_weight_g: 110,
    aliases: ["Chicken Thigh", "Chicken Thighs", "Skinless Chicken Thigh"],
  },
  {
    backbone_id: "seafood.salmon.fillet",
    canonical_name: "Salmon Fillet",
    taxonomy_subcategory: "Seafood",
    grocery_category: "Meat & Seafood",
    default_units: ["g", "oz", "lb", "each"],
    storage_hints: ["fridge", "freezer"],
    shelf_life_fridge_days: 2,
    shelf_life_freezer_days: 90,
    packaged_common: true,
    canonical_unit_weight_g: 170,
    aliases: ["Salmon", "Atlantic Salmon", "Sockeye Salmon"],
  },
  {
    backbone_id: "seafood.shrimp",
    canonical_name: "Shrimp",
    taxonomy_subcategory: "Seafood",
    grocery_category: "Meat & Seafood",
    default_units: ["g", "oz", "lb", "each"],
    storage_hints: ["fridge", "freezer"],
    shelf_life_fridge_days: 2,
    shelf_life_freezer_days: 180,
    packaged_common: true,
    aliases: ["Prawns", "Prawn", "Jumbo Shrimp", "Large Shrimp"],
  },

  // -----------------------------------------------------------------------
  // Dried fruit / beverages / alcohol / ferments
  // -----------------------------------------------------------------------
  {
    backbone_id: "dried-fruit.raisin",
    canonical_name: "Raisins",
    taxonomy_subcategory: "Dried Fruit",
    grocery_category: "Pantry",
    default_units: ["g", "oz", "cup"],
    storage_hints: ["pantry"],
    packaged_common: true,
    aliases: ["Raisin", "Golden Raisins", "Sultanas"],
  },
  {
    backbone_id: "dried-fruit.medjool-date",
    canonical_name: "Medjool Date",
    variant: "medjool",
    taxonomy_subcategory: "Dried Fruit",
    grocery_category: "Pantry",
    default_units: ["g", "oz", "each", "cup"],
    storage_hints: ["pantry", "fridge"],
    packaged_common: true,
    canonical_unit_weight_g: 24,
    aliases: ["Medjool Dates", "Fresh Medjool Dates", "Date", "Dates"],
  },
  {
    backbone_id: "ferments.kimchi",
    canonical_name: "Kimchi",
    taxonomy_subcategory: "Pickles & Ferments",
    grocery_category: "Produce",
    default_units: ["g", "oz", "cup"],
    storage_hints: ["fridge"],
    shelf_life_fridge_days: 60,
    packaged_common: true,
    is_composite: true,
    aliases: ["Napa Cabbage Kimchi", "Baechu Kimchi"],
  },
  {
    backbone_id: "alcohol.wine.dry-white",
    canonical_name: "Dry White Wine",
    variant: "dry white",
    taxonomy_subcategory: "Alcohol",
    grocery_category: "Beverages",
    default_units: ["ml", "oz", "cup", "bottle"],
    storage_hints: ["pantry", "fridge"],
    packaged_common: true,
    density_g_per_ml: 0.99,
    aliases: ["White Wine", "Sauvignon Blanc", "Pinot Grigio", "Pinot Gris"],
  },
];
